// Top 100 common verbs for kids.
// Each: base (present), past, future, emoji, kid-friendly example sentences for each tense.
// Future tense uses simple "will + base" form for clarity.
const VERBS = [
  { base:"be",       past:"was",        future:"will be",       emoji:"😊", ex:{past:"I was happy.", present:"I am happy.", future:"I will be happy."} },
  { base:"have",     past:"had",        future:"will have",     emoji:"🎁", ex:{past:"I had a gift.", present:"I have a gift.", future:"I will have a gift."} },
  { base:"do",       past:"did",        future:"will do",       emoji:"🛠️", ex:{past:"I did my work.", present:"I do my work.", future:"I will do my work."} },
  { base:"say",      past:"said",       future:"will say",      emoji:"💬", ex:{past:"She said hi.", present:"She says hi.", future:"She will say hi."} },
  { base:"go",       past:"went",       future:"will go",       emoji:"🚶", ex:{past:"I went to school.", present:"I go to school.", future:"I will go to school."} },
  { base:"get",      past:"got",        future:"will get",      emoji:"🎈", ex:{past:"He got a balloon.", present:"He gets a balloon.", future:"He will get a balloon."} },
  { base:"make",     past:"made",       future:"will make",     emoji:"🍪", ex:{past:"We made cookies.", present:"We make cookies.", future:"We will make cookies."} },
  { base:"know",     past:"knew",       future:"will know",     emoji:"🧠", ex:{past:"I knew the answer.", present:"I know the answer.", future:"I will know the answer."} },
  { base:"think",    past:"thought",    future:"will think",    emoji:"💭", ex:{past:"I thought about it.", present:"I think about it.", future:"I will think about it."} },
  { base:"take",     past:"took",       future:"will take",     emoji:"🎒", ex:{past:"She took her bag.", present:"She takes her bag.", future:"She will take her bag."} },
  { base:"see",      past:"saw",        future:"will see",      emoji:"👀", ex:{past:"I saw a bird.", present:"I see a bird.", future:"I will see a bird."} },
  { base:"come",     past:"came",       future:"will come",     emoji:"🚪", ex:{past:"He came home.", present:"He comes home.", future:"He will come home."} },
  { base:"want",     past:"wanted",     future:"will want",     emoji:"🍦", ex:{past:"I wanted ice cream.", present:"I want ice cream.", future:"I will want ice cream."} },
  { base:"look",     past:"looked",     future:"will look",     emoji:"🔍", ex:{past:"We looked at it.", present:"We look at it.", future:"We will look at it."} },
  { base:"use",      past:"used",       future:"will use",      emoji:"✂️", ex:{past:"I used scissors.", present:"I use scissors.", future:"I will use scissors."} },
  { base:"find",     past:"found",      future:"will find",     emoji:"🧩", ex:{past:"I found a clue.", present:"I find a clue.", future:"I will find a clue."} },
  { base:"give",     past:"gave",       future:"will give",     emoji:"🎁", ex:{past:"She gave a hug.", present:"She gives a hug.", future:"She will give a hug."} },
  { base:"tell",     past:"told",       future:"will tell",     emoji:"🗣️", ex:{past:"He told a story.", present:"He tells a story.", future:"He will tell a story."} },
  { base:"work",     past:"worked",     future:"will work",     emoji:"💼", ex:{past:"Mom worked today.", present:"Mom works today.", future:"Mom will work today."} },
  { base:"call",     past:"called",     future:"will call",     emoji:"📞", ex:{past:"I called grandma.", present:"I call grandma.", future:"I will call grandma."} },
  { base:"try",      past:"tried",      future:"will try",      emoji:"💪", ex:{past:"I tried my best.", present:"I try my best.", future:"I will try my best."} },
  { base:"ask",      past:"asked",      future:"will ask",      emoji:"❓", ex:{past:"She asked a question.", present:"She asks a question.", future:"She will ask a question."} },
  { base:"need",     past:"needed",     future:"will need",     emoji:"🆘", ex:{past:"I needed help.", present:"I need help.", future:"I will need help."} },
  { base:"feel",     past:"felt",       future:"will feel",     emoji:"❤️", ex:{past:"I felt happy.", present:"I feel happy.", future:"I will feel happy."} },
  { base:"become",   past:"became",     future:"will become",   emoji:"🦋", ex:{past:"It became a butterfly.", present:"It becomes a butterfly.", future:"It will become a butterfly."} },
  { base:"leave",    past:"left",       future:"will leave",    emoji:"👋", ex:{past:"We left the park.", present:"We leave the park.", future:"We will leave the park."} },
  { base:"put",      past:"put",        future:"will put",      emoji:"📦", ex:{past:"I put it down.", present:"I put it down.", future:"I will put it down."} },
  { base:"mean",     past:"meant",      future:"will mean",     emoji:"📖", ex:{past:"It meant yes.", present:"It means yes.", future:"It will mean yes."} },
  { base:"keep",     past:"kept",       future:"will keep",     emoji:"🔐", ex:{past:"He kept the secret.", present:"He keeps the secret.", future:"He will keep the secret."} },
  { base:"let",      past:"let",        future:"will let",      emoji:"🟢", ex:{past:"Mom let me play.", present:"Mom lets me play.", future:"Mom will let me play."} },
  { base:"begin",    past:"began",      future:"will begin",    emoji:"🏁", ex:{past:"It began to rain.", present:"It begins to rain.", future:"It will begin to rain."} },
  { base:"seem",     past:"seemed",     future:"will seem",     emoji:"🤔", ex:{past:"He seemed tired.", present:"He seems tired.", future:"He will seem tired."} },
  { base:"help",     past:"helped",     future:"will help",     emoji:"🤝", ex:{past:"I helped my friend.", present:"I help my friend.", future:"I will help my friend."} },
  { base:"talk",     past:"talked",     future:"will talk",     emoji:"🗨️", ex:{past:"We talked a lot.", present:"We talk a lot.", future:"We will talk a lot."} },
  { base:"turn",     past:"turned",     future:"will turn",     emoji:"🔄", ex:{past:"I turned around.", present:"I turn around.", future:"I will turn around."} },
  { base:"start",    past:"started",    future:"will start",    emoji:"🚦", ex:{past:"The race started.", present:"The race starts.", future:"The race will start."} },
  { base:"show",     past:"showed",     future:"will show",     emoji:"🖼️", ex:{past:"She showed me.", present:"She shows me.", future:"She will show me."} },
  { base:"hear",     past:"heard",      future:"will hear",     emoji:"👂", ex:{past:"I heard a song.", present:"I hear a song.", future:"I will hear a song."} },
  { base:"play",     past:"played",     future:"will play",     emoji:"🎮", ex:{past:"We played a game.", present:"We play a game.", future:"We will play a game."} },
  { base:"run",      past:"ran",        future:"will run",      emoji:"🏃", ex:{past:"He ran fast.", present:"He runs fast.", future:"He will run fast."} },
  { base:"move",     past:"moved",      future:"will move",     emoji:"📦", ex:{past:"We moved the box.", present:"We move the box.", future:"We will move the box."} },
  { base:"like",     past:"liked",      future:"will like",     emoji:"👍", ex:{past:"I liked it.", present:"I like it.", future:"I will like it."} },
  { base:"live",     past:"lived",      future:"will live",     emoji:"🏠", ex:{past:"We lived here.", present:"We live here.", future:"We will live here."} },
  { base:"believe",  past:"believed",   future:"will believe",  emoji:"✨", ex:{past:"I believed him.", present:"I believe him.", future:"I will believe him."} },
  { base:"hold",     past:"held",       future:"will hold",     emoji:"🤲", ex:{past:"She held my hand.", present:"She holds my hand.", future:"She will hold my hand."} },
  { base:"bring",    past:"brought",    future:"will bring",    emoji:"🎂", ex:{past:"I brought a cake.", present:"I bring a cake.", future:"I will bring a cake."} },
  { base:"happen",   past:"happened",   future:"will happen",   emoji:"⚡", ex:{past:"It happened fast.", present:"It happens fast.", future:"It will happen fast."} },
  { base:"write",    past:"wrote",      future:"will write",    emoji:"✏️", ex:{past:"I wrote a note.", present:"I write a note.", future:"I will write a note."} },
  { base:"sit",      past:"sat",        future:"will sit",      emoji:"🪑", ex:{past:"He sat down.", present:"He sits down.", future:"He will sit down."} },
  { base:"stand",    past:"stood",      future:"will stand",    emoji:"🧍", ex:{past:"She stood still.", present:"She stands still.", future:"She will stand still."} },
  { base:"lose",     past:"lost",       future:"will lose",     emoji:"😢", ex:{past:"I lost my hat.", present:"I lose my hat.", future:"I will lose my hat."} },
  { base:"pay",      past:"paid",       future:"will pay",      emoji:"💵", ex:{past:"Dad paid the bill.", present:"Dad pays the bill.", future:"Dad will pay the bill."} },
  { base:"meet",     past:"met",        future:"will meet",     emoji:"🤝", ex:{past:"We met at the park.", present:"We meet at the park.", future:"We will meet at the park."} },
  { base:"include",  past:"included",   future:"will include",  emoji:"➕", ex:{past:"I included you.", present:"I include you.", future:"I will include you."} },
  { base:"continue", past:"continued",  future:"will continue", emoji:"➡️", ex:{past:"We continued reading.", present:"We continue reading.", future:"We will continue reading."} },
  { base:"set",      past:"set",        future:"will set",      emoji:"🍽️", ex:{past:"I set the table.", present:"I set the table.", future:"I will set the table."} },
  { base:"learn",    past:"learned",    future:"will learn",    emoji:"📚", ex:{past:"I learned a song.", present:"I learn a song.", future:"I will learn a song."} },
  { base:"change",   past:"changed",    future:"will change",   emoji:"🔁", ex:{past:"It changed color.", present:"It changes color.", future:"It will change color."} },
  { base:"lead",     past:"led",        future:"will lead",     emoji:"🚩", ex:{past:"She led the way.", present:"She leads the way.", future:"She will lead the way."} },
  { base:"understand",past:"understood",future:"will understand",emoji:"💡",ex:{past:"I understood it.", present:"I understand it.", future:"I will understand it."} },
  { base:"watch",    past:"watched",    future:"will watch",    emoji:"📺", ex:{past:"We watched a show.", present:"We watch a show.", future:"We will watch a show."} },
  { base:"follow",   past:"followed",   future:"will follow",   emoji:"👣", ex:{past:"The dog followed me.", present:"The dog follows me.", future:"The dog will follow me."} },
  { base:"stop",     past:"stopped",    future:"will stop",     emoji:"🛑", ex:{past:"The bus stopped.", present:"The bus stops.", future:"The bus will stop."} },
  { base:"create",   past:"created",    future:"will create",   emoji:"🎨", ex:{past:"I created art.", present:"I create art.", future:"I will create art."} },
  { base:"speak",    past:"spoke",      future:"will speak",    emoji:"🗣️", ex:{past:"He spoke softly.", present:"He speaks softly.", future:"He will speak softly."} },
  { base:"read",     past:"read",       future:"will read",     emoji:"📖", ex:{past:"I read a book.", present:"I read a book.", future:"I will read a book."} },
  { base:"spend",    past:"spent",      future:"will spend",    emoji:"💸", ex:{past:"We spent a dollar.", present:"We spend a dollar.", future:"We will spend a dollar."} },
  { base:"grow",     past:"grew",       future:"will grow",     emoji:"🌱", ex:{past:"The plant grew.", present:"The plant grows.", future:"The plant will grow."} },
  { base:"open",     past:"opened",     future:"will open",     emoji:"🚪", ex:{past:"He opened the door.", present:"He opens the door.", future:"He will open the door."} },
  { base:"walk",     past:"walked",     future:"will walk",     emoji:"🚶", ex:{past:"We walked home.", present:"We walk home.", future:"We will walk home."} },
  { base:"win",      past:"won",        future:"will win",      emoji:"🏆", ex:{past:"She won the race.", present:"She wins the race.", future:"She will win the race."} },
  { base:"teach",    past:"taught",     future:"will teach",    emoji:"👩‍🏫", ex:{past:"He taught me.", present:"He teaches me.", future:"He will teach me."} },
  { base:"offer",    past:"offered",    future:"will offer",    emoji:"🤲", ex:{past:"I offered help.", present:"I offer help.", future:"I will offer help."} },
  { base:"remember", past:"remembered", future:"will remember", emoji:"🧠", ex:{past:"I remembered my book.", present:"I remember my book.", future:"I will remember my book."} },
  { base:"love",     past:"loved",      future:"will love",     emoji:"💖", ex:{past:"I loved the song.", present:"I love the song.", future:"I will love the song."} },
  { base:"consider", past:"considered", future:"will consider", emoji:"🤔", ex:{past:"I considered it.", present:"I consider it.", future:"I will consider it."} },
  { base:"appear",   past:"appeared",   future:"will appear",   emoji:"✨", ex:{past:"A star appeared.", present:"A star appears.", future:"A star will appear."} },
  { base:"buy",      past:"bought",     future:"will buy",      emoji:"🛒", ex:{past:"We bought milk.", present:"We buy milk.", future:"We will buy milk."} },
  { base:"wait",     past:"waited",     future:"will wait",     emoji:"⏳", ex:{past:"I waited a little.", present:"I wait a little.", future:"I will wait a little."} },
  { base:"serve",    past:"served",     future:"will serve",    emoji:"🍽️", ex:{past:"They served lunch.", present:"They serve lunch.", future:"They will serve lunch."} },
  { base:"die",      past:"died",       future:"will die",      emoji:"🥀", ex:{past:"The flower died.", present:"The flower dies.", future:"The flower will die."} },
  { base:"send",     past:"sent",       future:"will send",     emoji:"📨", ex:{past:"I sent a card.", present:"I send a card.", future:"I will send a card."} },
  { base:"build",    past:"built",      future:"will build",    emoji:"🏗️", ex:{past:"We built a fort.", present:"We build a fort.", future:"We will build a fort."} },
  { base:"stay",     past:"stayed",     future:"will stay",     emoji:"🛏️", ex:{past:"I stayed home.", present:"I stay home.", future:"I will stay home."} },
  { base:"fall",     past:"fell",       future:"will fall",     emoji:"🍂", ex:{past:"A leaf fell.", present:"A leaf falls.", future:"A leaf will fall."} },
  { base:"cut",      past:"cut",        future:"will cut",      emoji:"✂️", ex:{past:"I cut the paper.", present:"I cut the paper.", future:"I will cut the paper."} },
  { base:"reach",    past:"reached",    future:"will reach",    emoji:"🙆", ex:{past:"He reached the top.", present:"He reaches the top.", future:"He will reach the top."} },
  { base:"kill",     past:"killed",     future:"will kill",     emoji:"🦟", ex:{past:"We killed time.", present:"We kill time.", future:"We will kill time."} },
  { base:"remain",   past:"remained",   future:"will remain",   emoji:"🪨", ex:{past:"It remained quiet.", present:"It remains quiet.", future:"It will remain quiet."} },
  { base:"suggest",  past:"suggested",  future:"will suggest",  emoji:"💡", ex:{past:"I suggested a game.", present:"I suggest a game.", future:"I will suggest a game."} },
  { base:"raise",    past:"raised",     future:"will raise",    emoji:"🙋", ex:{past:"She raised her hand.", present:"She raises her hand.", future:"She will raise her hand."} },
  { base:"pass",     past:"passed",     future:"will pass",     emoji:"⚽", ex:{past:"He passed the ball.", present:"He passes the ball.", future:"He will pass the ball."} },
  { base:"sell",     past:"sold",       future:"will sell",     emoji:"🏷️", ex:{past:"They sold cookies.", present:"They sell cookies.", future:"They will sell cookies."} },
  { base:"require",  past:"required",   future:"will require",  emoji:"📋", ex:{past:"It required help.", present:"It requires help.", future:"It will require help."} },
  { base:"report",   past:"reported",   future:"will report",   emoji:"📝", ex:{past:"I reported the news.", present:"I report the news.", future:"I will report the news."} },
  { base:"decide",   past:"decided",    future:"will decide",   emoji:"✅", ex:{past:"We decided to go.", present:"We decide to go.", future:"We will decide to go."} },
  { base:"pull",     past:"pulled",     future:"will pull",     emoji:"🪢", ex:{past:"I pulled the rope.", present:"I pull the rope.", future:"I will pull the rope."} },
  { base:"return",   past:"returned",   future:"will return",   emoji:"↩️", ex:{past:"She returned home.", present:"She returns home.", future:"She will return home."} },
  { base:"explain",  past:"explained",  future:"will explain",  emoji:"🧑‍🏫", ex:{past:"He explained it.", present:"He explains it.", future:"He will explain it."} },
  { base:"hope",     past:"hoped",      future:"will hope",     emoji:"🌟", ex:{past:"I hoped for sun.", present:"I hope for sun.", future:"I will hope for sun."} },
  { base:"develop",  past:"developed",  future:"will develop",  emoji:"🌳", ex:{past:"It developed wings.", present:"It develops wings.", future:"It will develop wings."} },
  { base:"carry",    past:"carried",    future:"will carry",    emoji:"🎒", ex:{past:"I carried my bag.", present:"I carry my bag.", future:"I will carry my bag."} },
  { base:"break",    past:"broke",      future:"will break",    emoji:"💔", ex:{past:"It broke in two.", present:"It breaks in two.", future:"It will break in two."} },
  { base:"receive",  past:"received",   future:"will receive",  emoji:"📬", ex:{past:"I received a letter.", present:"I receive a letter.", future:"I will receive a letter."} },
  { base:"agree",    past:"agreed",     future:"will agree",    emoji:"🙌", ex:{past:"We agreed to share.", present:"We agree to share.", future:"We will agree to share."} },
  { base:"support",  past:"supported",  future:"will support",  emoji:"🤗", ex:{past:"I supported my friend.", present:"I support my friend.", future:"I will support my friend."} },
  { base:"hit",      past:"hit",        future:"will hit",      emoji:"⚾", ex:{past:"She hit the ball.", present:"She hits the ball.", future:"She will hit the ball."} },
  { base:"produce",  past:"produced",   future:"will produce",  emoji:"🏭", ex:{past:"The bee produced honey.", present:"The bee produces honey.", future:"The bee will produce honey."} },
  { base:"eat",      past:"ate",        future:"will eat",      emoji:"🍎", ex:{past:"I ate an apple.", present:"I eat an apple.", future:"I will eat an apple."} },
  { base:"cover",    past:"covered",    future:"will cover",    emoji:"🛌", ex:{past:"Snow covered the lawn.", present:"Snow covers the lawn.", future:"Snow will cover the lawn."} },
  { base:"catch",    past:"caught",     future:"will catch",    emoji:"🥎", ex:{past:"He caught the ball.", present:"He catches the ball.", future:"He will catch the ball."} },
  { base:"draw",     past:"drew",       future:"will draw",     emoji:"🖍️", ex:{past:"She drew a cat.", present:"She draws a cat.", future:"She will draw a cat."} },
  { base:"choose",   past:"chose",      future:"will choose",   emoji:"🧁", ex:{past:"I chose a cupcake.", present:"I choose a cupcake.", future:"I will choose a cupcake."} },
  { base:"sing",     past:"sang",       future:"will sing",     emoji:"🎤", ex:{past:"We sang a song.", present:"We sing a song.", future:"We will sing a song."} },
  { base:"sleep",    past:"slept",      future:"will sleep",    emoji:"😴", ex:{past:"The cat slept.", present:"The cat sleeps.", future:"The cat will sleep."} },
  { base:"drink",    past:"drank",      future:"will drink",    emoji:"🥛", ex:{past:"I drank milk.", present:"I drink milk.", future:"I will drink milk."} },
  { base:"swim",     past:"swam",       future:"will swim",     emoji:"🏊", ex:{past:"We swam in the pool.", present:"We swim in the pool.", future:"We will swim in the pool."} },
  { base:"jump",     past:"jumped",     future:"will jump",     emoji:"🦘", ex:{past:"He jumped high.", present:"He jumps high.", future:"He will jump high."} },
  { base:"fly",      past:"flew",       future:"will fly",      emoji:"🕊️", ex:{past:"The bird flew.", present:"The bird flies.", future:"The bird will fly."} },
  { base:"laugh",    past:"laughed",    future:"will laugh",    emoji:"😂", ex:{past:"We laughed a lot.", present:"We laugh a lot.", future:"We will laugh a lot."} },
  { base:"cry",      past:"cried",      future:"will cry",      emoji:"😭", ex:{past:"The baby cried.", present:"The baby cries.", future:"The baby will cry."} },
  { base:"dance",    past:"danced",     future:"will dance",    emoji:"💃", ex:{past:"We danced together.", present:"We dance together.", future:"We will dance together."} },
  { base:"throw",    past:"threw",      future:"will throw",    emoji:"🥏", ex:{past:"I threw the disc.", present:"I throw the disc.", future:"I will throw the disc."} },
  { base:"climb",    past:"climbed",    future:"will climb",    emoji:"🧗", ex:{past:"She climbed the tree.", present:"She climbs the tree.", future:"She will climb the tree."} },
  { base:"wash",     past:"washed",     future:"will wash",     emoji:"🧼", ex:{past:"I washed my hands.", present:"I wash my hands.", future:"I will wash my hands."} },
  { base:"smile",    past:"smiled",     future:"will smile",    emoji:"😄", ex:{past:"He smiled at me.", present:"He smiles at me.", future:"He will smile at me."} }
];
