// Daroach Learning — verb data
// Each verb: base, past, future, emoji, examples (past/present/future),
//   def  -> short kid-friendly definition (English)
//   pa   -> Punjabi (Gurmukhi script) translation of the base form
const VERBS = [
  { base:"be",       past:"was",        future:"will be",       emoji:"😊", def:"to exist or live", pa:"ਹੋਣਾ", ex:{past:"I was happy.", present:"I am happy.", future:"I will be happy."} },
  { base:"have",     past:"had",        future:"will have",     emoji:"🎁", def:"to own or hold something", pa:"ਰੱਖਣਾ", ex:{past:"I had a gift.", present:"I have a gift.", future:"I will have a gift."} },
  { base:"do",       past:"did",        future:"will do",       emoji:"🛠️", def:"to perform an action", pa:"ਕਰਨਾ", ex:{past:"I did my work.", present:"I do my work.", future:"I will do my work."} },
  { base:"say",      past:"said",       future:"will say",      emoji:"💬", def:"to speak words out loud", pa:"ਕਹਿਣਾ", ex:{past:"She said hi.", present:"She says hi.", future:"She will say hi."} },
  { base:"go",       past:"went",       future:"will go",       emoji:"🚶", def:"to move from one place to another", pa:"ਜਾਣਾ", ex:{past:"I went to school.", present:"I go to school.", future:"I will go to school."} },
  { base:"get",      past:"got",        future:"will get",      emoji:"🎈", def:"to receive or obtain something", pa:"ਲੈਣਾ", ex:{past:"He got a balloon.", present:"He gets a balloon.", future:"He will get a balloon."} },
  { base:"make",     past:"made",       future:"will make",     emoji:"🍪", def:"to create or build something", pa:"ਬਣਾਉਣਾ", ex:{past:"We made cookies.", present:"We make cookies.", future:"We will make cookies."} },
  { base:"know",     past:"knew",       future:"will know",     emoji:"🧠", def:"to have facts in your mind", pa:"ਜਾਣਨਾ", ex:{past:"I knew the answer.", present:"I know the answer.", future:"I will know the answer."} },
  { base:"think",    past:"thought",    future:"will think",    emoji:"💭", def:"to use your brain to reason", pa:"ਸੋਚਣਾ", ex:{past:"I thought about it.", present:"I think about it.", future:"I will think about it."} },
  { base:"take",     past:"took",       future:"will take",     emoji:"🎒", def:"to grab or carry something", pa:"ਲੈਣਾ", ex:{past:"She took her bag.", present:"She takes her bag.", future:"She will take her bag."} },
  { base:"see",      past:"saw",        future:"will see",      emoji:"👀", def:"to look at with your eyes", pa:"ਵੇਖਣਾ", ex:{past:"I saw a bird.", present:"I see a bird.", future:"I will see a bird."} },
  { base:"come",     past:"came",       future:"will come",     emoji:"🚪", def:"to move toward a place", pa:"ਆਉਣਾ", ex:{past:"He came home.", present:"He comes home.", future:"He will come home."} },
  { base:"want",     past:"wanted",     future:"will want",     emoji:"🍦", def:"to wish for something", pa:"ਚਾਹੁਣਾ", ex:{past:"I wanted ice cream.", present:"I want ice cream.", future:"I will want ice cream."} },
  { base:"look",     past:"looked",     future:"will look",     emoji:"🔍", def:"to turn your eyes toward something", pa:"ਵੇਖਣਾ", ex:{past:"We looked at it.", present:"We look at it.", future:"We will look at it."} },
  { base:"use",      past:"used",       future:"will use",      emoji:"✂️", def:"to put something to work", pa:"ਵਰਤਣਾ", ex:{past:"I used scissors.", present:"I use scissors.", future:"I will use scissors."} },
  { base:"find",     past:"found",      future:"will find",     emoji:"🧩", def:"to discover something", pa:"ਲੱਭਣਾ", ex:{past:"I found a clue.", present:"I find a clue.", future:"I will find a clue."} },
  { base:"give",     past:"gave",       future:"will give",     emoji:"🎁", def:"to hand something to someone", pa:"ਦੇਣਾ", ex:{past:"She gave a hug.", present:"She gives a hug.", future:"She will give a hug."} },
  { base:"tell",     past:"told",       future:"will tell",     emoji:"🗣️", def:"to share information by speaking", pa:"ਦੱਸਣਾ", ex:{past:"He told a story.", present:"He tells a story.", future:"He will tell a story."} },
  { base:"work",     past:"worked",     future:"will work",     emoji:"💼", def:"to do a job or task", pa:"ਕੰਮ ਕਰਨਾ", ex:{past:"Mom worked today.", present:"Mom works today.", future:"Mom will work today."} },
  { base:"call",     past:"called",     future:"will call",     emoji:"📞", def:"to phone or shout to someone", pa:"ਬੁਲਾਉਣਾ", ex:{past:"I called grandma.", present:"I call grandma.", future:"I will call grandma."} },
  { base:"try",      past:"tried",      future:"will try",      emoji:"💪", def:"to make an effort", pa:"ਕੋਸ਼ਿਸ਼ ਕਰਨਾ", ex:{past:"I tried my best.", present:"I try my best.", future:"I will try my best."} },
  { base:"ask",      past:"asked",      future:"will ask",      emoji:"❓", def:"to say a question", pa:"ਪੁੱਛਣਾ", ex:{past:"She asked a question.", present:"She asks a question.", future:"She will ask a question."} },
  { base:"need",     past:"needed",     future:"will need",     emoji:"🆘", def:"to require something important", pa:"ਲੋੜ ਹੋਣਾ", ex:{past:"I needed help.", present:"I need help.", future:"I will need help."} },
  { base:"feel",     past:"felt",       future:"will feel",     emoji:"❤️", def:"to sense an emotion or touch", pa:"ਮਹਿਸੂਸ ਕਰਨਾ", ex:{past:"I felt happy.", present:"I feel happy.", future:"I will feel happy."} },
  { base:"become",   past:"became",     future:"will become",   emoji:"🦋", def:"to change into something new", pa:"ਬਣਨਾ", ex:{past:"It became a butterfly.", present:"It becomes a butterfly.", future:"It will become a butterfly."} },
  { base:"leave",    past:"left",       future:"will leave",    emoji:"👋", def:"to go away from a place", pa:"ਛੱਡਣਾ", ex:{past:"We left the park.", present:"We leave the park.", future:"We will leave the park."} },
  { base:"put",      past:"put",        future:"will put",      emoji:"📦", def:"to place something somewhere", pa:"ਰੱਖਣਾ", ex:{past:"I put it down.", present:"I put it down.", future:"I will put it down."} },
  { base:"mean",     past:"meant",      future:"will mean",     emoji:"📖", def:"to have a certain meaning", pa:"ਮਤਲਬ ਹੋਣਾ", ex:{past:"It meant yes.", present:"It means yes.", future:"It will mean yes."} },
  { base:"keep",     past:"kept",       future:"will keep",     emoji:"🔐", def:"to hold on to something", pa:"ਰੱਖਣਾ", ex:{past:"He kept the secret.", present:"He keeps the secret.", future:"He will keep the secret."} },
  { base:"let",      past:"let",        future:"will let",      emoji:"🟢", def:"to allow something to happen", pa:"ਆਗਿਆ ਦੇਣਾ", ex:{past:"Mom let me play.", present:"Mom lets me play.", future:"Mom will let me play."} },
  { base:"begin",    past:"began",      future:"will begin",    emoji:"🏁", def:"to start something", pa:"ਸ਼ੁਰੂ ਕਰਨਾ", ex:{past:"It began to rain.", present:"It begins to rain.", future:"It will begin to rain."} },
  { base:"seem",     past:"seemed",     future:"will seem",     emoji:"🤔", def:"to appear to be a certain way", pa:"ਲੱਗਣਾ", ex:{past:"He seemed tired.", present:"He seems tired.", future:"He will seem tired."} },
  { base:"help",     past:"helped",     future:"will help",     emoji:"🤝", def:"to give support to someone", pa:"ਮਦਦ ਕਰਨਾ", ex:{past:"I helped my friend.", present:"I help my friend.", future:"I will help my friend."} },
  { base:"talk",     past:"talked",     future:"will talk",     emoji:"🗨️", def:"to speak with someone", pa:"ਗੱਲ ਕਰਨਾ", ex:{past:"We talked a lot.", present:"We talk a lot.", future:"We will talk a lot."} },
  { base:"turn",     past:"turned",     future:"will turn",     emoji:"🔄", def:"to change direction", pa:"ਮੁੜਨਾ", ex:{past:"I turned around.", present:"I turn around.", future:"I will turn around."} },
  { base:"start",    past:"started",    future:"will start",    emoji:"🚦", def:"to begin", pa:"ਸ਼ੁਰੂ ਕਰਨਾ", ex:{past:"The race started.", present:"The race starts.", future:"The race will start."} },
  { base:"show",     past:"showed",     future:"will show",     emoji:"🖼️", def:"to let someone see something", pa:"ਦਿਖਾਉਣਾ", ex:{past:"She showed me.", present:"She shows me.", future:"She will show me."} },
  { base:"hear",     past:"heard",      future:"will hear",     emoji:"👂", def:"to notice sound with your ears", pa:"ਸੁਣਨਾ", ex:{past:"I heard a song.", present:"I hear a song.", future:"I will hear a song."} },
  { base:"play",     past:"played",     future:"will play",     emoji:"🎮", def:"to have fun with a game", pa:"ਖੇਡਣਾ", ex:{past:"We played a game.", present:"We play a game.", future:"We will play a game."} },
  { base:"run",      past:"ran",        future:"will run",      emoji:"🏃", def:"to move on your feet quickly", pa:"ਦੌੜਨਾ", ex:{past:"He ran fast.", present:"He runs fast.", future:"He will run fast."} },
  { base:"move",     past:"moved",      future:"will move",     emoji:"📦", def:"to change position", pa:"ਹਿਲਾਉਣਾ", ex:{past:"We moved the box.", present:"We move the box.", future:"We will move the box."} },
  { base:"like",     past:"liked",      future:"will like",     emoji:"👍", def:"to enjoy something", pa:"ਪਸੰਦ ਕਰਨਾ", ex:{past:"I liked it.", present:"I like it.", future:"I will like it."} },
  { base:"live",     past:"lived",      future:"will live",     emoji:"🏠", def:"to be alive or to dwell somewhere", pa:"ਰਹਿਣਾ", ex:{past:"We lived here.", present:"We live here.", future:"We will live here."} },
  { base:"believe",  past:"believed",   future:"will believe",  emoji:"✨", def:"to think something is true", pa:"ਯਕੀਨ ਕਰਨਾ", ex:{past:"I believed him.", present:"I believe him.", future:"I will believe him."} },
  { base:"hold",     past:"held",       future:"will hold",     emoji:"🤲", def:"to keep something in your hand", pa:"ਫੜਨਾ", ex:{past:"She held my hand.", present:"She holds my hand.", future:"She will hold my hand."} },
  { base:"bring",    past:"brought",    future:"will bring",    emoji:"🎂", def:"to carry something here", pa:"ਲਿਆਉਣਾ", ex:{past:"I brought a cake.", present:"I bring a cake.", future:"I will bring a cake."} },
  { base:"happen",   past:"happened",   future:"will happen",   emoji:"⚡", def:"to take place", pa:"ਵਾਪਰਨਾ", ex:{past:"It happened fast.", present:"It happens fast.", future:"It will happen fast."} },
  { base:"write",    past:"wrote",      future:"will write",    emoji:"✏️", def:"to put words on paper", pa:"ਲਿਖਣਾ", ex:{past:"I wrote a note.", present:"I write a note.", future:"I will write a note."} },
  { base:"sit",      past:"sat",        future:"will sit",      emoji:"🪑", def:"to rest on a chair or seat", pa:"ਬੈਠਣਾ", ex:{past:"He sat down.", present:"He sits down.", future:"He will sit down."} },
  { base:"stand",    past:"stood",      future:"will stand",    emoji:"🧍", def:"to be on your feet", pa:"ਖੜਨਾ", ex:{past:"She stood still.", present:"She stands still.", future:"She will stand still."} },
  { base:"lose",     past:"lost",       future:"will lose",     emoji:"😢", def:"to no longer have something", pa:"ਗੁਆਉਣਾ", ex:{past:"I lost my hat.", present:"I lose my hat.", future:"I will lose my hat."} },
  { base:"pay",      past:"paid",       future:"will pay",      emoji:"💵", def:"to give money for something", pa:"ਭੁਗਤਾਨ ਕਰਨਾ", ex:{past:"Dad paid the bill.", present:"Dad pays the bill.", future:"Dad will pay the bill."} },
  { base:"meet",     past:"met",        future:"will meet",     emoji:"🤝", def:"to come together with someone", pa:"ਮਿਲਣਾ", ex:{past:"We met at the park.", present:"We meet at the park.", future:"We will meet at the park."} },
  { base:"include",  past:"included",   future:"will include",  emoji:"➕", def:"to make part of a group", pa:"ਸ਼ਾਮਲ ਕਰਨਾ", ex:{past:"I included you.", present:"I include you.", future:"I will include you."} },
  { base:"continue", past:"continued",  future:"will continue", emoji:"➡️", def:"to keep going", pa:"ਜਾਰੀ ਰੱਖਣਾ", ex:{past:"We continued reading.", present:"We continue reading.", future:"We will continue reading."} },
  { base:"set",      past:"set",        future:"will set",      emoji:"🍽️", def:"to place something carefully", pa:"ਰੱਖਣਾ", ex:{past:"I set the table.", present:"I set the table.", future:"I will set the table."} },
  { base:"learn",    past:"learned",    future:"will learn",    emoji:"📚", def:"to gain knowledge or skill", pa:"ਸਿੱਖਣਾ", ex:{past:"I learned a song.", present:"I learn a song.", future:"I will learn a song."} },
  { base:"change",   past:"changed",    future:"will change",   emoji:"🔁", def:"to make different", pa:"ਬਦਲਣਾ", ex:{past:"It changed color.", present:"It changes color.", future:"It will change color."} },
  { base:"lead",     past:"led",        future:"will lead",     emoji:"🚩", def:"to guide others", pa:"ਅਗਵਾਈ ਕਰਨਾ", ex:{past:"She led the way.", present:"She leads the way.", future:"She will lead the way."} },
  { base:"understand",past:"understood",future:"will understand",emoji:"💡", def:"to know how something works", pa:"ਸਮਝਣਾ", ex:{past:"I understood it.", present:"I understand it.", future:"I will understand it."} },
  { base:"watch",    past:"watched",    future:"will watch",    emoji:"📺", def:"to look at something for a while", pa:"ਦੇਖਣਾ", ex:{past:"We watched a show.", present:"We watch a show.", future:"We will watch a show."} },
  { base:"follow",   past:"followed",   future:"will follow",   emoji:"👣", def:"to go after someone", pa:"ਪਿੱਛੇ ਜਾਣਾ", ex:{past:"The dog followed me.", present:"The dog follows me.", future:"The dog will follow me."} },
  { base:"stop",     past:"stopped",    future:"will stop",     emoji:"🛑", def:"to no longer move or do", pa:"ਰੁਕਣਾ", ex:{past:"The bus stopped.", present:"The bus stops.", future:"The bus will stop."} },
  { base:"create",   past:"created",    future:"will create",   emoji:"🎨", def:"to make something new", pa:"ਬਣਾਉਣਾ", ex:{past:"I created art.", present:"I create art.", future:"I will create art."} },
  { base:"speak",    past:"spoke",      future:"will speak",    emoji:"🗣️", def:"to use your voice in words", pa:"ਬੋਲਣਾ", ex:{past:"He spoke softly.", present:"He speaks softly.", future:"He will speak softly."} },
  { base:"read",     past:"read",       future:"will read",     emoji:"📖", def:"to look at words and understand", pa:"ਪੜ੍ਹਨਾ", ex:{past:"I read a book.", present:"I read a book.", future:"I will read a book."} },
  { base:"spend",    past:"spent",      future:"will spend",    emoji:"💸", def:"to use up money or time", pa:"ਖਰਚਣਾ", ex:{past:"We spent a dollar.", present:"We spend a dollar.", future:"We will spend a dollar."} },
  { base:"grow",     past:"grew",       future:"will grow",     emoji:"🌱", def:"to get bigger over time", pa:"ਵਧਣਾ", ex:{past:"The plant grew.", present:"The plant grows.", future:"The plant will grow."} },
  { base:"open",     past:"opened",     future:"will open",     emoji:"🚪", def:"to no longer be closed", pa:"ਖੋਲ੍ਹਣਾ", ex:{past:"He opened the door.", present:"He opens the door.", future:"He will open the door."} },
  { base:"walk",     past:"walked",     future:"will walk",     emoji:"🚶", def:"to move on your feet slowly", pa:"ਤੁਰਨਾ", ex:{past:"We walked home.", present:"We walk home.", future:"We will walk home."} },
  { base:"win",      past:"won",        future:"will win",      emoji:"🏆", def:"to come first in a contest", pa:"ਜਿੱਤਣਾ", ex:{past:"She won the race.", present:"She wins the race.", future:"She will win the race."} },
  { base:"teach",    past:"taught",     future:"will teach",    emoji:"👩‍🏫", def:"to help others learn", pa:"ਸਿਖਾਉਣਾ", ex:{past:"He taught me.", present:"He teaches me.", future:"He will teach me."} },
  { base:"offer",    past:"offered",    future:"will offer",    emoji:"🤲", def:"to present something to someone", pa:"ਪੇਸ਼ ਕਰਨਾ", ex:{past:"I offered help.", present:"I offer help.", future:"I will offer help."} },
  { base:"remember", past:"remembered", future:"will remember", emoji:"🧠", def:"to keep in your memory", pa:"ਯਾਦ ਰੱਖਣਾ", ex:{past:"I remembered my book.", present:"I remember my book.", future:"I will remember my book."} },
  { base:"love",     past:"loved",      future:"will love",     emoji:"💖", def:"to care about deeply", pa:"ਪਿਆਰ ਕਰਨਾ", ex:{past:"I loved the song.", present:"I love the song.", future:"I will love the song."} },
  { base:"consider", past:"considered", future:"will consider", emoji:"🤔", def:"to think carefully about", pa:"ਵਿਚਾਰਨਾ", ex:{past:"I considered it.", present:"I consider it.", future:"I will consider it."} },
  { base:"appear",   past:"appeared",   future:"will appear",   emoji:"✨", def:"to show up or be seen", pa:"ਨਜ਼ਰ ਆਉਣਾ", ex:{past:"A star appeared.", present:"A star appears.", future:"A star will appear."} },
  { base:"buy",      past:"bought",     future:"will buy",      emoji:"🛒", def:"to get something with money", pa:"ਖਰੀਦਣਾ", ex:{past:"We bought milk.", present:"We buy milk.", future:"We will buy milk."} },
  { base:"wait",     past:"waited",     future:"will wait",     emoji:"⏳", def:"to stay until something happens", pa:"ਉਡੀਕਣਾ", ex:{past:"I waited a little.", present:"I wait a little.", future:"I will wait a little."} },
  { base:"serve",    past:"served",     future:"will serve",    emoji:"🍽️", def:"to give food or help to others", pa:"ਸੇਵਾ ਕਰਨਾ", ex:{past:"They served lunch.", present:"They serve lunch.", future:"They will serve lunch."} },
  { base:"die",      past:"died",       future:"will die",      emoji:"🥀", def:"to stop being alive", pa:"ਮਰਨਾ", ex:{past:"The flower died.", present:"The flower dies.", future:"The flower will die."} },
  { base:"send",     past:"sent",       future:"will send",     emoji:"📨", def:"to make something go to someone", pa:"ਭੇਜਣਾ", ex:{past:"I sent a card.", present:"I send a card.", future:"I will send a card."} },
  { base:"build",    past:"built",      future:"will build",    emoji:"🏗️", def:"to put pieces together to make something", pa:"ਬਣਾਉਣਾ", ex:{past:"We built a fort.", present:"We build a fort.", future:"We will build a fort."} },
  { base:"stay",     past:"stayed",     future:"will stay",     emoji:"🛏️", def:"to remain in a place", pa:"ਰਹਿਣਾ", ex:{past:"I stayed home.", present:"I stay home.", future:"I will stay home."} },
  { base:"fall",     past:"fell",       future:"will fall",     emoji:"🍂", def:"to drop down", pa:"ਡਿੱਗਣਾ", ex:{past:"A leaf fell.", present:"A leaf falls.", future:"A leaf will fall."} },
  { base:"cut",      past:"cut",        future:"will cut",      emoji:"✂️", def:"to slice with something sharp", pa:"ਕੱਟਣਾ", ex:{past:"I cut the paper.", present:"I cut the paper.", future:"I will cut the paper."} },
  { base:"reach",    past:"reached",    future:"will reach",    emoji:"🙆", def:"to arrive at a place", pa:"ਪਹੁੰਚਣਾ", ex:{past:"He reached the top.", present:"He reaches the top.", future:"He will reach the top."} },
  { base:"kill",     past:"killed",     future:"will kill",     emoji:"🦟", def:"to end something's life", pa:"ਮਾਰਨਾ", ex:{past:"We killed time.", present:"We kill time.", future:"We will kill time."} },
  { base:"remain",   past:"remained",   future:"will remain",   emoji:"🪨", def:"to stay the same", pa:"ਰਹਿਣਾ", ex:{past:"It remained quiet.", present:"It remains quiet.", future:"It will remain quiet."} },
  { base:"suggest",  past:"suggested",  future:"will suggest",  emoji:"💡", def:"to offer an idea", pa:"ਸੁਝਾਉਣਾ", ex:{past:"I suggested a game.", present:"I suggest a game.", future:"I will suggest a game."} },
  { base:"raise",    past:"raised",     future:"will raise",    emoji:"🙋", def:"to lift something up", pa:"ਚੁੱਕਣਾ", ex:{past:"She raised her hand.", present:"She raises her hand.", future:"She will raise her hand."} },
  { base:"pass",     past:"passed",     future:"will pass",     emoji:"⚽", def:"to send or move along", pa:"ਪਾਸ ਕਰਨਾ", ex:{past:"He passed the ball.", present:"He passes the ball.", future:"He will pass the ball."} },
  { base:"sell",     past:"sold",       future:"will sell",     emoji:"🏷️", def:"to give something for money", pa:"ਵੇਚਣਾ", ex:{past:"They sold cookies.", present:"They sell cookies.", future:"They will sell cookies."} },
  { base:"require",  past:"required",   future:"will require",  emoji:"📋", def:"to need something", pa:"ਲੋੜ ਪੈਣਾ", ex:{past:"It required help.", present:"It requires help.", future:"It will require help."} },
  { base:"report",   past:"reported",   future:"will report",   emoji:"📝", def:"to tell about what happened", pa:"ਰਿਪੋਰਟ ਕਰਨਾ", ex:{past:"I reported the news.", present:"I report the news.", future:"I will report the news."} },
  { base:"decide",   past:"decided",    future:"will decide",   emoji:"✅", def:"to make up your mind", pa:"ਫੈਸਲਾ ਕਰਨਾ", ex:{past:"We decided to go.", present:"We decide to go.", future:"We will decide to go."} },
  { base:"pull",     past:"pulled",     future:"will pull",     emoji:"🪢", def:"to drag toward you", pa:"ਖਿੱਚਣਾ", ex:{past:"I pulled the rope.", present:"I pull the rope.", future:"I will pull the rope."} },
  { base:"return",   past:"returned",   future:"will return",   emoji:"↩️", def:"to come back", pa:"ਵਾਪਸ ਆਉਣਾ", ex:{past:"She returned home.", present:"She returns home.", future:"She will return home."} },
  { base:"explain",  past:"explained",  future:"will explain",  emoji:"🧑‍🏫", def:"to make something clear", pa:"ਸਮਝਾਉਣਾ", ex:{past:"He explained it.", present:"He explains it.", future:"He will explain it."} },
  { base:"hope",     past:"hoped",      future:"will hope",     emoji:"🌟", def:"to wish for something good", pa:"ਉਮੀਦ ਕਰਨਾ", ex:{past:"I hoped for sun.", present:"I hope for sun.", future:"I will hope for sun."} },
  { base:"develop",  past:"developed",  future:"will develop",  emoji:"🌳", def:"to grow or get better", pa:"ਵਿਕਸਤ ਹੋਣਾ", ex:{past:"It developed wings.", present:"It develops wings.", future:"It will develop wings."} },
  { base:"carry",    past:"carried",    future:"will carry",    emoji:"🎒", def:"to hold and move something", pa:"ਚੁੱਕਣਾ", ex:{past:"I carried my bag.", present:"I carry my bag.", future:"I will carry my bag."} },
  { base:"break",    past:"broke",      future:"will break",    emoji:"💔", def:"to make something fall apart", pa:"ਤੋੜਨਾ", ex:{past:"It broke in two.", present:"It breaks in two.", future:"It will break in two."} },
  { base:"receive",  past:"received",   future:"will receive",  emoji:"📬", def:"to get something given to you", pa:"ਪ੍ਰਾਪਤ ਕਰਨਾ", ex:{past:"I received a letter.", present:"I receive a letter.", future:"I will receive a letter."} },
  { base:"agree",    past:"agreed",     future:"will agree",    emoji:"🙌", def:"to say yes to something", pa:"ਸਹਿਮਤ ਹੋਣਾ", ex:{past:"We agreed to share.", present:"We agree to share.", future:"We will agree to share."} },
  { base:"support",  past:"supported",  future:"will support",  emoji:"🤗", def:"to help and stand with", pa:"ਸਹਾਇਤਾ ਕਰਨਾ", ex:{past:"I supported my friend.", present:"I support my friend.", future:"I will support my friend."} },
  { base:"hit",      past:"hit",        future:"will hit",      emoji:"⚾", def:"to strike with force", pa:"ਮਾਰਨਾ", ex:{past:"She hit the ball.", present:"She hits the ball.", future:"She will hit the ball."} },
  { base:"produce",  past:"produced",   future:"will produce",  emoji:"🏭", def:"to make or grow something", pa:"ਪੈਦਾ ਕਰਨਾ", ex:{past:"The bee produced honey.", present:"The bee produces honey.", future:"The bee will produce honey."} },
  { base:"eat",      past:"ate",        future:"will eat",      emoji:"🍎", def:"to put food in your mouth", pa:"ਖਾਣਾ", ex:{past:"I ate an apple.", present:"I eat an apple.", future:"I will eat an apple."} },
  { base:"cover",    past:"covered",    future:"will cover",    emoji:"🛌", def:"to put something over", pa:"ਢੱਕਣਾ", ex:{past:"Snow covered the lawn.", present:"Snow covers the lawn.", future:"Snow will cover the lawn."} },
  { base:"catch",    past:"caught",     future:"will catch",    emoji:"🥎", def:"to grab something moving", pa:"ਫੜਨਾ", ex:{past:"He caught the ball.", present:"He catches the ball.", future:"He will catch the ball."} },
  { base:"draw",     past:"drew",       future:"will draw",     emoji:"🖍️", def:"to make a picture with lines", pa:"ਚਿੱਤਰ ਬਣਾਉਣਾ", ex:{past:"She drew a cat.", present:"She draws a cat.", future:"She will draw a cat."} },
  { base:"choose",   past:"chose",      future:"will choose",   emoji:"🧁", def:"to pick one of many", pa:"ਚੁਣਨਾ", ex:{past:"I chose a cupcake.", present:"I choose a cupcake.", future:"I will choose a cupcake."} },
  { base:"sing",     past:"sang",       future:"will sing",     emoji:"🎤", def:"to make musical sounds with your voice", pa:"ਗਾਉਣਾ", ex:{past:"We sang a song.", present:"We sing a song.", future:"We will sing a song."} },
  { base:"sleep",    past:"slept",      future:"will sleep",    emoji:"😴", def:"to rest with eyes closed", pa:"ਸੌਣਾ", ex:{past:"The cat slept.", present:"The cat sleeps.", future:"The cat will sleep."} },
  { base:"drink",    past:"drank",      future:"will drink",    emoji:"🥛", def:"to swallow a liquid", pa:"ਪੀਣਾ", ex:{past:"I drank milk.", present:"I drink milk.", future:"I will drink milk."} },
  { base:"swim",     past:"swam",       future:"will swim",     emoji:"🏊", def:"to move through water", pa:"ਤੈਰਨਾ", ex:{past:"We swam in the pool.", present:"We swim in the pool.", future:"We will swim in the pool."} },
  { base:"jump",     past:"jumped",     future:"will jump",     emoji:"🦘", def:"to push off the ground into the air", pa:"ਛਾਲ ਮਾਰਨਾ", ex:{past:"He jumped high.", present:"He jumps high.", future:"He will jump high."} },
  { base:"fly",      past:"flew",       future:"will fly",      emoji:"🕊️", def:"to move through the air", pa:"ਉੱਡਣਾ", ex:{past:"The bird flew.", present:"The bird flies.", future:"The bird will fly."} },
  { base:"laugh",    past:"laughed",    future:"will laugh",    emoji:"😂", def:"to make a happy sound", pa:"ਹੱਸਣਾ", ex:{past:"We laughed a lot.", present:"We laugh a lot.", future:"We will laugh a lot."} },
  { base:"cry",      past:"cried",      future:"will cry",      emoji:"😭", def:"to shed tears", pa:"ਰੋਣਾ", ex:{past:"The baby cried.", present:"The baby cries.", future:"The baby will cry."} },
  { base:"dance",    past:"danced",     future:"will dance",    emoji:"💃", def:"to move your body to music", pa:"ਨੱਚਣਾ", ex:{past:"We danced together.", present:"We dance together.", future:"We will dance together."} },
  { base:"throw",    past:"threw",      future:"will throw",    emoji:"🥏", def:"to send something through the air with your arm", pa:"ਸੁੱਟਣਾ", ex:{past:"I threw the disc.", present:"I throw the disc.", future:"I will throw the disc."} },
  { base:"climb",    past:"climbed",    future:"will climb",    emoji:"🧗", def:"to go up using hands and feet", pa:"ਚੜ੍ਹਨਾ", ex:{past:"She climbed the tree.", present:"She climbs the tree.", future:"She will climb the tree."} },
  { base:"wash",     past:"washed",     future:"will wash",     emoji:"🧼", def:"to clean with water", pa:"ਧੋਣਾ", ex:{past:"I washed my hands.", present:"I wash my hands.", future:"I will wash my hands."} },
  { base:"smile",    past:"smiled",     future:"will smile",    emoji:"😄", def:"to turn your mouth up in joy", pa:"ਮੁਸਕਰਾਉਣਾ", ex:{past:"He smiled at me.", present:"He smiles at me.", future:"He will smile at me."} },
  // ---- Expanded set ----
  { base:"cook",     past:"cooked",     future:"will cook",     emoji:"🍳", def:"to prepare food with heat", pa:"ਪਕਾਉਣਾ", ex:{past:"Mom cooked dinner.", present:"Mom cooks dinner.", future:"Mom will cook dinner."} },
  { base:"bake",     past:"baked",      future:"will bake",     emoji:"🥧", def:"to cook food in an oven", pa:"ਪਕਾਉਣਾ", ex:{past:"We baked a pie.", present:"We bake a pie.", future:"We will bake a pie."} },
  { base:"clean",    past:"cleaned",    future:"will clean",    emoji:"🧹", def:"to make tidy or free of dirt", pa:"ਸਾਫ਼ ਕਰਨਾ", ex:{past:"I cleaned my room.", present:"I clean my room.", future:"I will clean my room."} },
  { base:"close",    past:"closed",     future:"will close",    emoji:"🚪", def:"to shut something", pa:"ਬੰਦ ਕਰਨਾ", ex:{past:"He closed the door.", present:"He closes the door.", future:"He will close the door."} },
  { base:"drive",    past:"drove",      future:"will drive",    emoji:"🚗", def:"to operate a vehicle", pa:"ਚਲਾਉਣਾ", ex:{past:"Dad drove the car.", present:"Dad drives the car.", future:"Dad will drive the car."} },
  { base:"ride",     past:"rode",       future:"will ride",     emoji:"🚲", def:"to sit on something that moves", pa:"ਸਵਾਰੀ ਕਰਨਾ", ex:{past:"I rode my bike.", present:"I ride my bike.", future:"I will ride my bike."} },
  { base:"sing",     past:"sang",       future:"will sing",     emoji:"🎵", def:"to make music with your voice", pa:"ਗਾਉਣਾ", ex:{past:"They sang loudly.", present:"They sing loudly.", future:"They will sing loudly."} },
  { base:"paint",    past:"painted",    future:"will paint",    emoji:"🖌️", def:"to put color on something", pa:"ਰੰਗਣਾ", ex:{past:"She painted a wall.", present:"She paints a wall.", future:"She will paint a wall."} },
  { base:"plant",    past:"planted",    future:"will plant",    emoji:"🌳", def:"to put a seed in the ground", pa:"ਲਾਉਣਾ", ex:{past:"We planted a tree.", present:"We plant a tree.", future:"We will plant a tree."} },
  { base:"water",    past:"watered",    future:"will water",    emoji:"💧", def:"to give water to plants", pa:"ਪਾਣੀ ਦੇਣਾ", ex:{past:"I watered the plant.", present:"I water the plant.", future:"I will water the plant."} },
  { base:"open",     past:"opened",     future:"will open",     emoji:"📂", def:"to make something not closed", pa:"ਖੋਲ੍ਹਣਾ", ex:{past:"She opened her book.", present:"She opens her book.", future:"She will open her book."} },
  { base:"sweep",    past:"swept",      future:"will sweep",    emoji:"🧹", def:"to clean a floor with a broom", pa:"ਝਾੜਨਾ", ex:{past:"He swept the floor.", present:"He sweeps the floor.", future:"He will sweep the floor."} },
  { base:"share",    past:"shared",     future:"will share",    emoji:"🤝", def:"to give part to others", pa:"ਸਾਂਝਾ ਕਰਨਾ", ex:{past:"We shared our snacks.", present:"We share our snacks.", future:"We will share our snacks."} },
  { base:"listen",   past:"listened",   future:"will listen",   emoji:"👂", def:"to pay attention with your ears", pa:"ਸੁਣਨਾ", ex:{past:"I listened closely.", present:"I listen closely.", future:"I will listen closely."} },
  { base:"answer",   past:"answered",   future:"will answer",   emoji:"💬", def:"to reply to a question", pa:"ਜਵਾਬ ਦੇਣਾ", ex:{past:"She answered me.", present:"She answers me.", future:"She will answer me."} },
  { base:"count",    past:"counted",    future:"will count",    emoji:"🔢", def:"to say numbers in order", pa:"ਗਿਣਨਾ", ex:{past:"He counted the coins.", present:"He counts the coins.", future:"He will count the coins."} },
  { base:"add",      past:"added",      future:"will add",      emoji:"➕", def:"to put together to make more", pa:"ਜੋੜਨਾ", ex:{past:"I added two and two.", present:"I add two and two.", future:"I will add two and two."} },
  { base:"subtract", past:"subtracted", future:"will subtract", emoji:"➖", def:"to take away to make less", pa:"ਘਟਾਉਣਾ", ex:{past:"She subtracted three.", present:"She subtracts three.", future:"She will subtract three."} },
  { base:"measure",  past:"measured",   future:"will measure",  emoji:"📏", def:"to find the size of something", pa:"ਮਾਪਣਾ", ex:{past:"We measured the desk.", present:"We measure the desk.", future:"We will measure the desk."} },
  { base:"build",    past:"built",      future:"will build",    emoji:"🧱", def:"to put pieces together", pa:"ਉਸਾਰਨਾ", ex:{past:"They built a wall.", present:"They build a wall.", future:"They will build a wall."} },
  { base:"fix",      past:"fixed",      future:"will fix",      emoji:"🔧", def:"to repair something broken", pa:"ਠੀਕ ਕਰਨਾ", ex:{past:"Dad fixed the bike.", present:"Dad fixes the bike.", future:"Dad will fix the bike."} },
  { base:"travel",   past:"traveled",   future:"will travel",   emoji:"✈️", def:"to go to far places", pa:"ਯਾਤਰਾ ਕਰਨਾ", ex:{past:"We traveled by train.", present:"We travel by train.", future:"We will travel by train."} },
  { base:"visit",    past:"visited",    future:"will visit",    emoji:"🏡", def:"to go see someone or someplace", pa:"ਮਿਲਣ ਜਾਣਾ", ex:{past:"I visited my aunt.", present:"I visit my aunt.", future:"I will visit my aunt."} },
  { base:"explore",  past:"explored",   future:"will explore",  emoji:"🗺️", def:"to look around a new place", pa:"ਖੋਜ ਕਰਨਾ", ex:{past:"We explored the cave.", present:"We explore the cave.", future:"We will explore the cave."} },
  { base:"discover", past:"discovered", future:"will discover", emoji:"🔍", def:"to find something new", pa:"ਖੋਜਣਾ", ex:{past:"She discovered a coin.", present:"She discovers a coin.", future:"She will discover a coin."} },
  { base:"hunt",     past:"hunted",     future:"will hunt",     emoji:"🏹", def:"to chase to catch", pa:"ਸ਼ਿਕਾਰ ਕਰਨਾ", ex:{past:"They hunted for clues.", present:"They hunt for clues.", future:"They will hunt for clues."} },
  { base:"protect",  past:"protected",  future:"will protect",  emoji:"🛡️", def:"to keep safe from harm", pa:"ਰੱਖਿਆ ਕਰਨਾ", ex:{past:"He protected the dog.", present:"He protects the dog.", future:"He will protect the dog."} },
  { base:"save",     past:"saved",      future:"will save",     emoji:"💾", def:"to keep for later", pa:"ਬਚਾਉਣਾ", ex:{past:"I saved my coins.", present:"I save my coins.", future:"I will save my coins."} },
  { base:"share",    past:"shared",     future:"will share",    emoji:"📤", def:"to give some to others", pa:"ਵੰਡਣਾ", ex:{past:"We shared the pizza.", present:"We share the pizza.", future:"We will share the pizza."} },
  { base:"borrow",   past:"borrowed",   future:"will borrow",   emoji:"📥", def:"to use something that's not yours for a time", pa:"ਉਧਾਰ ਲੈਣਾ", ex:{past:"I borrowed a pen.", present:"I borrow a pen.", future:"I will borrow a pen."} },
  { base:"lend",     past:"lent",       future:"will lend",     emoji:"🤲", def:"to let someone use your thing", pa:"ਉਧਾਰ ਦੇਣਾ", ex:{past:"She lent me a book.", present:"She lends me a book.", future:"She will lend me a book."} },
  { base:"forgive",  past:"forgave",    future:"will forgive",  emoji:"💞", def:"to stop being angry with someone", pa:"ਮਾਫ਼ ਕਰਨਾ", ex:{past:"I forgave my friend.", present:"I forgive my friend.", future:"I will forgive my friend."} },
  { base:"thank",    past:"thanked",    future:"will thank",    emoji:"🙏", def:"to say you are grateful", pa:"ਧੰਨਵਾਦ ਕਰਨਾ", ex:{past:"He thanked the teacher.", present:"He thanks the teacher.", future:"He will thank the teacher."} },
  { base:"greet",    past:"greeted",    future:"will greet",    emoji:"👋", def:"to say hello", pa:"ਨਮਸਕਾਰ ਕਰਨਾ", ex:{past:"She greeted us warmly.", present:"She greets us warmly.", future:"She will greet us warmly."} },
  { base:"bow",      past:"bowed",      future:"will bow",      emoji:"🙇", def:"to bend your head in respect", pa:"ਸਿਰ ਝੁਕਾਉਣਾ", ex:{past:"They bowed low.", present:"They bow low.", future:"They will bow low."} },
  { base:"hug",      past:"hugged",     future:"will hug",      emoji:"🤗", def:"to hold someone tightly with arms", pa:"ਜੱਫੀ ਪਾਉਣਾ", ex:{past:"Mom hugged me.", present:"Mom hugs me.", future:"Mom will hug me."} },
  { base:"kiss",     past:"kissed",     future:"will kiss",     emoji:"😘", def:"to touch with the lips lovingly", pa:"ਚੁੰਮਣਾ", ex:{past:"She kissed the baby.", present:"She kisses the baby.", future:"She will kiss the baby."} },
  { base:"shout",    past:"shouted",    future:"will shout",    emoji:"📢", def:"to say something very loudly", pa:"ਚੀਕਣਾ", ex:{past:"He shouted across the field.", present:"He shouts across the field.", future:"He will shout across the field."} },
  { base:"whisper",  past:"whispered",  future:"will whisper",  emoji:"🤫", def:"to talk very quietly", pa:"ਘੁਸਰ-ਮੁਸਰ ਕਰਨਾ", ex:{past:"She whispered a secret.", present:"She whispers a secret.", future:"She will whisper a secret."} },
  { base:"sneeze",   past:"sneezed",    future:"will sneeze",   emoji:"🤧", def:"to push air out your nose suddenly", pa:"ਛਿੱਕ ਮਾਰਨਾ", ex:{past:"I sneezed twice.", present:"I sneeze twice.", future:"I will sneeze twice."} },
  { base:"yawn",     past:"yawned",     future:"will yawn",     emoji:"😪", def:"to open your mouth when tired", pa:"ਉਬਾਸੀ ਲੈਣਾ", ex:{past:"He yawned in class.", present:"He yawns in class.", future:"He will yawn in class."} },
  { base:"blink",    past:"blinked",    future:"will blink",    emoji:"😉", def:"to close and open your eyes fast", pa:"ਪਲਕ ਮਾਰਨਾ", ex:{past:"She blinked twice.", present:"She blinks twice.", future:"She will blink twice."} },
  { base:"wave",     past:"waved",      future:"will wave",     emoji:"👋", def:"to move your hand to say hi", pa:"ਹੱਥ ਹਿਲਾਉਣਾ", ex:{past:"I waved goodbye.", present:"I wave goodbye.", future:"I will wave goodbye."} },
  { base:"clap",     past:"clapped",    future:"will clap",     emoji:"👏", def:"to hit your hands together", pa:"ਤਾੜੀ ਮਾਰਨਾ", ex:{past:"We clapped loudly.", present:"We clap loudly.", future:"We will clap loudly."} },
  { base:"point",    past:"pointed",    future:"will point",    emoji:"👉", def:"to show direction with a finger", pa:"ਇਸ਼ਾਰਾ ਕਰਨਾ", ex:{past:"He pointed at the bird.", present:"He points at the bird.", future:"He will point at the bird."} },
  { base:"kick",     past:"kicked",     future:"will kick",     emoji:"🦵", def:"to hit with your foot", pa:"ਠੋਕਰ ਮਾਰਨਾ", ex:{past:"She kicked the ball.", present:"She kicks the ball.", future:"She will kick the ball."} },
  { base:"push",     past:"pushed",     future:"will push",     emoji:"🤜", def:"to move something away from you", pa:"ਧੱਕਣਾ", ex:{past:"I pushed the door.", present:"I push the door.", future:"I will push the door."} },
  { base:"lift",     past:"lifted",     future:"will lift",     emoji:"💪", def:"to pick something up", pa:"ਚੁੱਕਣਾ", ex:{past:"He lifted the box.", present:"He lifts the box.", future:"He will lift the box."} },
  { base:"drop",     past:"dropped",    future:"will drop",     emoji:"📉", def:"to let something fall", pa:"ਡੇਗਣਾ", ex:{past:"I dropped my pen.", present:"I drop my pen.", future:"I will drop my pen."} },
  { base:"pour",     past:"poured",     future:"will pour",     emoji:"🫗", def:"to make liquid flow", pa:"ਡੋਲ੍ਹਣਾ", ex:{past:"She poured juice.", present:"She pours juice.", future:"She will pour juice."} },
  { base:"mix",      past:"mixed",      future:"will mix",      emoji:"🥣", def:"to stir together", pa:"ਮਿਲਾਉਣਾ", ex:{past:"We mixed the batter.", present:"We mix the batter.", future:"We will mix the batter."} },
  { base:"taste",    past:"tasted",     future:"will taste",    emoji:"👅", def:"to try food with your tongue", pa:"ਚੱਖਣਾ", ex:{past:"I tasted the soup.", present:"I taste the soup.", future:"I will taste the soup."} },
  { base:"smell",    past:"smelled",    future:"will smell",    emoji:"👃", def:"to use your nose to sense", pa:"ਸੁੰਘਣਾ", ex:{past:"She smelled flowers.", present:"She smells flowers.", future:"She will smell flowers."} },
  { base:"freeze",   past:"froze",      future:"will freeze",   emoji:"🧊", def:"to make very cold and hard", pa:"ਜੰਮਣਾ", ex:{past:"The water froze.", present:"The water freezes.", future:"The water will freeze."} },
  { base:"melt",     past:"melted",     future:"will melt",     emoji:"🫠", def:"to turn from solid to liquid", pa:"ਪਿਘਲਣਾ", ex:{past:"The ice melted.", present:"The ice melts.", future:"The ice will melt."} },
  { base:"boil",     past:"boiled",     future:"will boil",     emoji:"♨️", def:"to heat liquid until it bubbles", pa:"ਉਬਾਲਣਾ", ex:{past:"The kettle boiled.", present:"The kettle boils.", future:"The kettle will boil."} },
  { base:"shine",    past:"shone",      future:"will shine",    emoji:"☀️", def:"to give off bright light", pa:"ਚਮਕਣਾ", ex:{past:"The sun shone brightly.", present:"The sun shines brightly.", future:"The sun will shine brightly."} },
  { base:"snow",     past:"snowed",     future:"will snow",     emoji:"❄️", def:"to fall as soft white flakes", pa:"ਬਰਫ਼ ਪੈਣੀ", ex:{past:"It snowed all night.", present:"It snows all night.", future:"It will snow all night."} },
  { base:"rain",     past:"rained",     future:"will rain",     emoji:"🌧️", def:"to fall from the sky as water", pa:"ਮੀਂਹ ਪੈਣਾ", ex:{past:"It rained yesterday.", present:"It rains today.", future:"It will rain tomorrow."} },
  { base:"blow",     past:"blew",       future:"will blow",     emoji:"💨", def:"to push air with your mouth or wind", pa:"ਫੂਕਣਾ", ex:{past:"The wind blew hard.", present:"The wind blows hard.", future:"The wind will blow hard."} },
  { base:"ring",     past:"rang",       future:"will ring",     emoji:"🔔", def:"to make a bell sound", pa:"ਘੰਟੀ ਵਜਣਾ", ex:{past:"The bell rang.", present:"The bell rings.", future:"The bell will ring."} },
  { base:"knock",    past:"knocked",    future:"will knock",    emoji:"✊", def:"to tap to be let in", pa:"ਖੜਕਾਉਣਾ", ex:{past:"He knocked twice.", present:"He knocks twice.", future:"He will knock twice."} },
  { base:"sweat",    past:"sweat",      future:"will sweat",    emoji:"😅", def:"to drip water from skin when hot", pa:"ਪਸੀਨਾ ਆਉਣਾ", ex:{past:"He sweat a lot.", present:"He sweats a lot.", future:"He will sweat a lot."} },
  { base:"fight",    past:"fought",     future:"will fight",    emoji:"🥊", def:"to use force against someone", pa:"ਲੜਨਾ", ex:{past:"They fought bravely.", present:"They fight bravely.", future:"They will fight bravely."} },
  { base:"train",    past:"trained",    future:"will train",    emoji:"🥋", def:"to practice to get better", pa:"ਅਭਿਆਸ ਕਰਨਾ", ex:{past:"Goku trained hard.", present:"Goku trains hard.", future:"Goku will train hard."} },
  { base:"dream",    past:"dreamed",    future:"will dream",    emoji:"💤", def:"to see pictures in your sleep", pa:"ਸੁਪਨਾ ਵੇਖਣਾ", ex:{past:"I dreamed of dragons.", present:"I dream of dragons.", future:"I will dream of dragons."} },
  { base:"wish",     past:"wished",     future:"will wish",     emoji:"⭐", def:"to hope something will happen", pa:"ਇੱਛਾ ਕਰਨਾ", ex:{past:"She wished for snow.", present:"She wishes for snow.", future:"She will wish for snow."} },
  { base:"plan",     past:"planned",    future:"will plan",     emoji:"🗒️", def:"to think about what to do", pa:"ਯੋਜਨਾ ਬਣਾਉਣਾ", ex:{past:"We planned a trip.", present:"We plan a trip.", future:"We will plan a trip."} },
  { base:"finish",   past:"finished",   future:"will finish",   emoji:"🏁", def:"to bring to an end", pa:"ਖਤਮ ਕਰਨਾ", ex:{past:"I finished my homework.", present:"I finish my homework.", future:"I will finish my homework."} },
  { base:"start",    past:"started",    future:"will start",    emoji:"▶️", def:"to begin something", pa:"ਆਰੰਭ ਕਰਨਾ", ex:{past:"We started the game.", present:"We start the game.", future:"We will start the game."} },
  { base:"win",      past:"won",        future:"will win",      emoji:"🥇", def:"to come in first place", pa:"ਜਿੱਤਣਾ", ex:{past:"Our team won.", present:"Our team wins.", future:"Our team will win."} },
  { base:"lose",     past:"lost",       future:"will lose",     emoji:"😞", def:"to not win", pa:"ਹਾਰਨਾ", ex:{past:"They lost the match.", present:"They lose the match.", future:"They will lose the match."} },
  { base:"hide",     past:"hid",        future:"will hide",     emoji:"🙈", def:"to put out of sight", pa:"ਛੁਪਾਉਣਾ", ex:{past:"He hid the gift.", present:"He hides the gift.", future:"He will hide the gift."} },
  { base:"seek",     past:"sought",     future:"will seek",     emoji:"🕵️", def:"to look for something", pa:"ਖੋਜਣਾ", ex:{past:"I sought the truth.", present:"I seek the truth.", future:"I will seek the truth."} },
  { base:"chase",    past:"chased",     future:"will chase",    emoji:"🏃‍♂️", def:"to run after to catch", pa:"ਪਿੱਛਾ ਕਰਨਾ", ex:{past:"The dog chased the cat.", present:"The dog chases the cat.", future:"The dog will chase the cat."} },
  { base:"escape",   past:"escaped",    future:"will escape",   emoji:"🏃", def:"to get away from danger", pa:"ਬਚ ਨਿਕਲਣਾ", ex:{past:"They escaped safely.", present:"They escape safely.", future:"They will escape safely."} },
  { base:"answer",   past:"answered",   future:"will answer",   emoji:"📞", def:"to respond to a call or question", pa:"ਜਵਾਬ ਦੇਣਾ", ex:{past:"I answered the phone.", present:"I answer the phone.", future:"I will answer the phone."} },
  { base:"check",    past:"checked",    future:"will check",    emoji:"✔️", def:"to look to make sure", pa:"ਜਾਂਚ ਕਰਨਾ", ex:{past:"She checked her work.", present:"She checks her work.", future:"She will check her work."} },
  { base:"choose",   past:"chose",      future:"will choose",   emoji:"🎯", def:"to pick an option", pa:"ਚੁਣਨਾ", ex:{past:"He chose blue.", present:"He chooses blue.", future:"He will choose blue."} },
  { base:"compare",  past:"compared",   future:"will compare",  emoji:"⚖️", def:"to look at how things are alike or different", pa:"ਤੁਲਨਾ ਕਰਨਾ", ex:{past:"We compared sizes.", present:"We compare sizes.", future:"We will compare sizes."} },
  { base:"copy",     past:"copied",     future:"will copy",     emoji:"📝", def:"to make the same as another", pa:"ਨਕਲ ਕਰਨਾ", ex:{past:"I copied the picture.", present:"I copy the picture.", future:"I will copy the picture."} },
  { base:"guess",    past:"guessed",    future:"will guess",    emoji:"🎲", def:"to give an answer without being sure", pa:"ਅੰਦਾਜ਼ਾ ਲਾਉਣਾ", ex:{past:"He guessed the number.", present:"He guesses the number.", future:"He will guess the number."} },
  { base:"solve",    past:"solved",     future:"will solve",    emoji:"🧠", def:"to find an answer to a problem", pa:"ਹੱਲ ਕਰਨਾ", ex:{past:"She solved the puzzle.", present:"She solves the puzzle.", future:"She will solve the puzzle."} },
  { base:"study",    past:"studied",    future:"will study",    emoji:"📖", def:"to learn by reading and practicing", pa:"ਪੜ੍ਹਾਈ ਕਰਨਾ", ex:{past:"I studied math.", present:"I study math.", future:"I will study math."} },
  { base:"practice", past:"practiced",  future:"will practice", emoji:"🎹", def:"to do something often to get better", pa:"ਮਸ਼ਕ ਕਰਨਾ", ex:{past:"We practiced piano.", present:"We practice piano.", future:"We will practice piano."} },
  { base:"obey",     past:"obeyed",     future:"will obey",     emoji:"🫡", def:"to do what you are told", pa:"ਮੰਨਣਾ", ex:{past:"He obeyed the rules.", present:"He obeys the rules.", future:"He will obey the rules."} },
  { base:"laugh",    past:"laughed",    future:"will laugh",    emoji:"😆", def:"to giggle when something is funny", pa:"ਹੱਸਣਾ", ex:{past:"They laughed at the joke.", present:"They laugh at the joke.", future:"They will laugh at the joke."} },
  { base:"meditate", past:"meditated",  future:"will meditate", emoji:"🧘", def:"to sit quietly and calm your mind", pa:"ਧਿਆਨ ਕਰਨਾ", ex:{past:"He meditated each day.", present:"He meditates each day.", future:"He will meditate each day."} }
];

// ---- Nouns: things, people, places ----
const NOUNS = [
  { word:"dog",      def:"a friendly animal that barks",            pa:"ਕੁੱਤਾ",    emoji:"🐶" },
  { word:"cat",      def:"a small furry animal that meows",         pa:"ਬਿੱਲੀ",    emoji:"🐱" },
  { word:"bird",     def:"an animal with wings that can fly",       pa:"ਪੰਛੀ",     emoji:"🐦" },
  { word:"book",     def:"pages with words you can read",            pa:"ਕਿਤਾਬ",   emoji:"📚" },
  { word:"school",   def:"a place where children learn",            pa:"ਸਕੂਲ",    emoji:"🏫" },
  { word:"teacher",  def:"a person who helps others learn",         pa:"ਅਧਿਆਪਕ",  emoji:"👩‍🏫" },
  { word:"friend",   def:"someone you like and trust",              pa:"ਦੋਸਤ",    emoji:"🧑‍🤝‍🧑" },
  { word:"family",   def:"the people you live and grow with",       pa:"ਪਰਿਵਾਰ",  emoji:"👨‍👩‍👧" },
  { word:"house",    def:"a building where people live",            pa:"ਘਰ",      emoji:"🏠" },
  { word:"car",      def:"a vehicle with four wheels",              pa:"ਗੱਡੀ",    emoji:"🚗" },
  { word:"tree",     def:"a tall plant with a trunk and leaves",     pa:"ਰੁੱਖ",    emoji:"🌳" },
  { word:"river",    def:"a long stream of water",                   pa:"ਨਦੀ",     emoji:"🏞️" },
  { word:"mountain", def:"a very tall piece of land",                pa:"ਪਹਾੜ",    emoji:"⛰️" },
  { word:"sun",      def:"the bright star we see in the day",        pa:"ਸੂਰਜ",    emoji:"☀️" },
  { word:"moon",     def:"the round light we see at night",          pa:"ਚੰਦ",     emoji:"🌙" },
  { word:"star",     def:"a tiny twinkly light in the night sky",    pa:"ਤਾਰਾ",    emoji:"⭐" },
  { word:"water",    def:"the clear liquid we drink",                pa:"ਪਾਣੀ",    emoji:"💧" },
  { word:"food",     def:"what we eat to grow strong",               pa:"ਖਾਣਾ",    emoji:"🍱" },
  { word:"apple",    def:"a round red or green fruit",               pa:"ਸੇਬ",     emoji:"🍎" },
  { word:"milk",     def:"a white drink from cows",                  pa:"ਦੁੱਧ",    emoji:"🥛" },
  { word:"ball",     def:"a round toy you throw or kick",            pa:"ਗੇਂਦ",    emoji:"⚽" },
  { word:"toy",      def:"something you play with",                  pa:"ਖਿਡੌਣਾ",  emoji:"🧸" },
  { word:"bike",     def:"a vehicle with two wheels you pedal",       pa:"ਸਾਈਕਲ",   emoji:"🚲" },
  { word:"road",     def:"a hard path for cars to travel on",        pa:"ਸੜਕ",     emoji:"🛣️" },
  { word:"city",     def:"a big place with many people",             pa:"ਸ਼ਹਿਰ",   emoji:"🏙️" },
  { word:"village",  def:"a small place with a few homes",           pa:"ਪਿੰਡ",    emoji:"🏡" },
  { word:"sky",      def:"the open space above us",                  pa:"ਅਸਮਾਨ",   emoji:"🌤️" },
  { word:"cloud",    def:"a soft white shape in the sky",            pa:"ਬੱਦਲ",    emoji:"☁️" },
  { word:"flower",   def:"the colorful part of a plant",             pa:"ਫੁੱਲ",    emoji:"🌸" },
  { word:"fish",     def:"an animal that swims in water",            pa:"ਮੱਛੀ",    emoji:"🐟" },
  { word:"horse",    def:"a strong animal you can ride",             pa:"ਘੋੜਾ",    emoji:"🐴" },
  { word:"chair",    def:"a seat for one person",                    pa:"ਕੁਰਸੀ",   emoji:"🪑" },
  { word:"table",    def:"a flat top with legs for things",          pa:"ਮੇਜ਼",    emoji:"🪑" },
  { word:"door",     def:"the part of a wall you walk through",      pa:"ਦਰਵਾਜ਼ਾ", emoji:"🚪" },
  { word:"window",   def:"a glass opening to see outside",           pa:"ਖਿੜਕੀ",  emoji:"🪟" },
  { word:"sister",   def:"a female child of your parents",           pa:"ਭੈਣ",     emoji:"👧" },
  { word:"brother",  def:"a male child of your parents",             pa:"ਭਰਾ",     emoji:"👦" },
  { word:"mother",   def:"a female parent",                          pa:"ਮਾਂ",     emoji:"👩" },
  { word:"father",   def:"a male parent",                            pa:"ਪਿਤਾ",    emoji:"👨" },
  { word:"hand",     def:"the part of your arm with fingers",        pa:"ਹੱਥ",     emoji:"✋" },
  // ---- People & family ----
  { word:"baby",     def:"a very young child",                       pa:"ਬੱਚਾ",    emoji:"👶" },
  { word:"boy",      def:"a young male child",                       pa:"ਮੁੰਡਾ",   emoji:"👦" },
  { word:"girl",     def:"a young female child",                     pa:"ਕੁੜੀ",    emoji:"👧" },
  { word:"man",      def:"a grown-up male",                          pa:"ਆਦਮੀ",    emoji:"👨" },
  { word:"woman",    def:"a grown-up female",                        pa:"ਔਰਤ",     emoji:"👩" },
  { word:"grandma",  def:"the mother of your mom or dad",             pa:"ਦਾਦੀ/ਨਾਨੀ", emoji:"👵" },
  { word:"grandpa",  def:"the father of your mom or dad",             pa:"ਦਾਦਾ/ਨਾਨਾ", emoji:"👴" },
  { word:"uncle",    def:"your parent's brother",                    pa:"ਚਾਚਾ/ਮਾਮਾ", emoji:"🧔" },
  { word:"aunt",     def:"your parent's sister",                     pa:"ਚਾਚੀ/ਮਾਸੀ", emoji:"👩" },
  { word:"cousin",   def:"the child of your aunt or uncle",          pa:"ਚਚੇਰਾ ਭਰਾ/ਭੈਣ", emoji:"🧒" },
  { word:"doctor",   def:"a person who helps sick people",           pa:"ਡਾਕਟਰ",   emoji:"🧑‍⚕️" },
  { word:"farmer",   def:"a person who grows food",                  pa:"ਕਿਸਾਨ",   emoji:"🧑‍🌾" },
  { word:"chef",     def:"a person who cooks food",                  pa:"ਰਸੋਈਆ",   emoji:"👨‍🍳" },
  { word:"police",   def:"a person who keeps people safe",            pa:"ਪੁਲਿਸ",    emoji:"👮" },
  { word:"artist",   def:"a person who makes art",                   pa:"ਕਲਾਕਾਰ",  emoji:"🧑‍🎨" },
  { word:"singer",   def:"a person who sings songs",                 pa:"ਗਾਇਕ",    emoji:"🎤" },
  { word:"player",   def:"a person who plays a game",                pa:"ਖਿਡਾਰੀ",  emoji:"🏃" },
  { word:"king",     def:"a male royal ruler",                       pa:"ਰਾਜਾ",    emoji:"🤴" },
  { word:"queen",    def:"a female royal ruler",                     pa:"ਰਾਣੀ",    emoji:"👸" },
  // ---- Body parts ----
  { word:"head",     def:"the top part of your body",                pa:"ਸਿਰ",     emoji:"🧠" },
  { word:"eye",      def:"the part you see with",                    pa:"ਅੱਖ",     emoji:"👁️" },
  { word:"ear",      def:"the part you hear with",                   pa:"ਕੰਨ",     emoji:"👂" },
  { word:"nose",     def:"the part you smell with",                  pa:"ਨੱਕ",     emoji:"👃" },
  { word:"mouth",    def:"the part you eat and speak with",          pa:"ਮੂੰਹ",    emoji:"👄" },
  { word:"tooth",    def:"the hard white part inside your mouth",    pa:"ਦੰਦ",     emoji:"🦷" },
  { word:"tongue",   def:"the soft pink part you taste with",         pa:"ਜੀਭ",     emoji:"👅" },
  { word:"hair",     def:"the soft strands on your head",            pa:"ਵਾਲ",     emoji:"💇" },
  { word:"arm",      def:"the body part from shoulder to hand",       pa:"ਬਾਂਹ",    emoji:"💪" },
  { word:"leg",      def:"the body part you walk with",               pa:"ਲੱਤ",     emoji:"🦵" },
  { word:"foot",     def:"the body part at the bottom of the leg",    pa:"ਪੈਰ",     emoji:"🦶" },
  { word:"finger",   def:"one of five parts on each hand",            pa:"ਉਂਗਲੀ",   emoji:"👆" },
  { word:"heart",    def:"the part inside that pumps blood",          pa:"ਦਿਲ",     emoji:"❤️" },
  { word:"brain",    def:"the part inside your head you think with",  pa:"ਦਿਮਾਗ",   emoji:"🧠" },
  // ---- Animals ----
  { word:"cow",      def:"a large farm animal that gives milk",      pa:"ਗਾਂ",     emoji:"🐄" },
  { word:"sheep",    def:"a fluffy farm animal",                     pa:"ਭੇਡ",     emoji:"🐑" },
  { word:"goat",     def:"a horned farm animal",                     pa:"ਬੱਕਰੀ",   emoji:"🐐" },
  { word:"chicken",  def:"a farm bird that lays eggs",                pa:"ਮੁਰਗੀ",   emoji:"🐔" },
  { word:"duck",     def:"a water bird that quacks",                  pa:"ਬੱਤਖ",    emoji:"🦆" },
  { word:"pig",      def:"a pink farm animal",                       pa:"ਸੂਰ",     emoji:"🐷" },
  { word:"rabbit",   def:"a small animal with long ears",             pa:"ਖਰਗੋਸ਼",  emoji:"🐰" },
  { word:"mouse",    def:"a tiny animal with a long tail",            pa:"ਚੂਹਾ",    emoji:"🐭" },
  { word:"elephant", def:"a big animal with a long trunk",            pa:"ਹਾਥੀ",   emoji:"🐘" },
  { word:"tiger",    def:"a big striped wild cat",                   pa:"ਚੀਤਾ",   emoji:"🐯" },
  { word:"lion",     def:"a strong wild cat with a mane",             pa:"ਸ਼ੇਰ",    emoji:"🦁" },
  { word:"monkey",   def:"an animal that climbs trees",                pa:"ਬਾਂਦਰ",   emoji:"🐒" },
  { word:"bear",     def:"a big furry forest animal",                pa:"ਰਿੱਛ",    emoji:"🐻" },
  { word:"snake",    def:"a long animal with no legs",                pa:"ਸੱਪ",     emoji:"🐍" },
  { word:"frog",     def:"a small green animal that hops",            pa:"ਡੱਡੂ",    emoji:"🐸" },
  { word:"butterfly",def:"an insect with pretty wings",               pa:"ਤਿਤਲੀ",   emoji:"🦋" },
  { word:"bee",      def:"an insect that makes honey",                pa:"ਮੱਖੀ",    emoji:"🐝" },
  { word:"ant",      def:"a tiny insect that lives in groups",        pa:"ਕੀੜੀ",   emoji:"🐜" },
  { word:"spider",   def:"a small animal with eight legs",            pa:"ਮੱਕੜੀ",   emoji:"🕷️" },
  // ---- Places ----
  { word:"park",     def:"a place with grass and trees to play",      pa:"ਪਾਰਕ",    emoji:"🏞️" },
  { word:"hospital", def:"a place where sick people get better",      pa:"ਹਸਪਤਾਲ",  emoji:"🏥" },
  { word:"market",   def:"a place to buy food and things",            pa:"ਮੰਡੀ",     emoji:"🛒" },
  { word:"shop",     def:"a small place where things are sold",       pa:"ਦੁਕਾਨ",   emoji:"🏪" },
  { word:"library",  def:"a place full of books to read",             pa:"ਪੁਸਤਕਾਲਾ", emoji:"📚" },
  { word:"temple",   def:"a holy place to pray",                      pa:"ਮੰਦਰ",    emoji:"🛕" },
  { word:"farm",     def:"land where food is grown",                 pa:"ਖੇਤ",     emoji:"🚜" },
  { word:"beach",    def:"sandy land next to the sea",               pa:"ਤੱਟ",      emoji:"🏖️" },
  { word:"forest",   def:"a place full of trees",                    pa:"ਜੰਗਲ",    emoji:"🌲" },
  { word:"island",   def:"land surrounded by water",                  pa:"ਟਾਪੂ",    emoji:"🏝️" },
  { word:"ocean",    def:"a very big body of salty water",            pa:"ਸਮੁੰਦਰ",  emoji:"🌊" },
  { word:"lake",     def:"a large pool of fresh water",               pa:"ਝੀਲ",     emoji:"🏞️" },
  { word:"bridge",   def:"something built over water or a road",      pa:"ਪੁਲ",     emoji:"🌉" },
  { word:"airport",  def:"a place where planes land and take off",    pa:"ਹਵਾਈ ਅੱਡਾ", emoji:"✈️" },
  { word:"station",  def:"a place where trains or buses stop",         pa:"ਸਟੇਸ਼ਨ",  emoji:"🚉" },
  { word:"country",  def:"a large area with its own people and rules", pa:"ਦੇਸ਼",     emoji:"🌐" },
  { word:"world",    def:"the whole Earth and everything on it",       pa:"ਦੁਨੀਆ",   emoji:"🌍" },
  // ---- Food & drink ----
  { word:"bread",    def:"a soft food made from flour",              pa:"ਰੋਟੀ",    emoji:"🍞" },
  { word:"rice",     def:"small white grains that we cook",           pa:"ਚੌਲ",     emoji:"🍚" },
  { word:"egg",      def:"a round food that comes from chickens",     pa:"ਅੰਡਾ",    emoji:"🥚" },
  { word:"cheese",   def:"a food made from milk",                    pa:"ਪਨੀਰ",    emoji:"🧀" },
  { word:"butter",   def:"a soft yellow food made from milk",         pa:"ਮੱਖਣ",    emoji:"🧈" },
  { word:"sugar",    def:"a sweet white food",                       pa:"ਚੀਨੀ",    emoji:"🍬" },
  { word:"salt",     def:"a white food that makes things taste good",  pa:"ਨਮਕ",     emoji:"🧂" },
  { word:"banana",   def:"a long yellow fruit",                      pa:"ਕੇਲਾ",    emoji:"🍌" },
  { word:"orange",   def:"a round juicy citrus fruit",                pa:"ਸੰਤਰਾ",   emoji:"🍊" },
  { word:"mango",    def:"a sweet tropical fruit",                   pa:"ਅੰਬ",     emoji:"🥭" },
  { word:"grape",    def:"a tiny round fruit on a vine",             pa:"ਅੰਗੂਰ",   emoji:"🍇" },
  { word:"tea",      def:"a hot drink made from leaves",              pa:"ਚਾਹ",     emoji:"🍵" },
  { word:"juice",    def:"a drink made from fruit",                  pa:"ਜੂਸ",     emoji:"🧃" },
  // ---- Things at home / school ----
  { word:"bed",      def:"the place where you sleep",                pa:"ਮੰਜਾ",     emoji:"🛏️" },
  { word:"pillow",   def:"a soft cushion for your head",              pa:"ਸਿਰਹਾਣਾ", emoji:"🛏️" },
  { word:"blanket",  def:"a cover that keeps you warm",               pa:"ਕੰਬਲ",    emoji:"🛌" },
  { word:"clock",    def:"a tool that shows the time",                pa:"ਘੜੀ",     emoji:"🕰️" },
  { word:"phone",    def:"a tool you use to talk to people far away",  pa:"ਫ਼ੋਨ",    emoji:"📱" },
  { word:"computer", def:"a machine that helps with work and games",  pa:"ਕੰਪਿਊਟਰ", emoji:"💻" },
  { word:"pen",      def:"a tool you use to write",                  pa:"ਕਲਮ",     emoji:"🖊️" },
  { word:"pencil",   def:"a wooden tool you write with",              pa:"ਪੈਨਸਿਲ",  emoji:"✏️" },
  { word:"paper",    def:"a thin sheet you write on",                pa:"ਕਾਗਜ਼",    emoji:"📄" },
  { word:"bag",      def:"a thing you carry stuff in",                pa:"ਥੈਲਾ",    emoji:"🎒" },
  { word:"shoe",     def:"a cover for your foot",                    pa:"ਜੁੱਤਾ",    emoji:"👟" },
  { word:"shirt",    def:"clothing you wear on top",                  pa:"ਕਮੀਜ਼",    emoji:"👕" },
  { word:"hat",      def:"a cover for your head",                    pa:"ਟੋਪੀ",    emoji:"🎩" },
  { word:"key",      def:"a small tool to open locks",                pa:"ਚਾਬੀ",    emoji:"🔑" },
  { word:"map",      def:"a drawing that shows places",              pa:"ਨਕਸ਼ਾ",   emoji:"🗺️" },
  { word:"music",    def:"sounds that make a song",                  pa:"ਸੰਗੀਤ",   emoji:"🎶" },
  { word:"game",     def:"a fun activity with rules",                pa:"ਖੇਡ",     emoji:"🎮" },
  { word:"story",    def:"a tale told with words",                   pa:"ਕਹਾਣੀ",   emoji:"📖" },
  { word:"picture",  def:"a drawing or photo of something",          pa:"ਤਸਵੀਰ",   emoji:"🖼️" },
  { word:"letter",   def:"a message written on paper",               pa:"ਚਿੱਠੀ",   emoji:"✉️" },
  { word:"number",   def:"a symbol that shows how many",              pa:"ਨੰਬਰ",    emoji:"🔢" },
  { word:"name",     def:"the word people call you",                 pa:"ਨਾਮ",      emoji:"🏷️" },
  { word:"color",    def:"how something looks like red or blue",     pa:"ਰੰਗ",      emoji:"🎨" },
  { word:"shape",    def:"the form of a thing, like circle",         pa:"ਆਕਾਰ",   emoji:"🔺" }
];

// ---- Grammar concept cards (used in Train + Battle) ----
const GRAMMAR = [
  { term:"noun",      def:"a person, place, thing, or idea",
    examples:["dog","school","sky","love"],
    pa:"ਨਾਂਵ" },
  { term:"verb",      def:"an action word — something you do",
    examples:["run","jump","read","eat"],
    pa:"ਕਿਰਿਆ" },
  { term:"adjective", def:"a word that describes a noun",
    examples:["happy","tall","red","tiny"],
    pa:"ਵਿਸ਼ੇਸ਼ਣ" },
  { term:"adverb",    def:"a word that describes a verb (how something is done)",
    examples:["quickly","loudly","gently","soon"],
    pa:"ਕਿਰਿਆ-ਵਿਸ਼ੇਸ਼ਣ" },
  { term:"pronoun",   def:"a word that takes the place of a noun",
    examples:["he","she","it","they"],
    pa:"ਪੜਨਾਂਵ" },
  { term:"preposition", def:"a word that shows place or time, like in/on/under",
    examples:["in","on","under","before"],
    pa:"ਸੰਬੰਧਕ" },
  { term:"sentence",  def:"a group of words that tells a complete idea",
    examples:["The cat sleeps.","I love mom.","Birds fly."],
    pa:"ਵਾਕ" },
  { term:"past tense", def:"talks about something that already happened",
    examples:["walked","ate","saw","ran"],
    pa:"ਭੂਤ ਕਾਲ" },
  { term:"present tense", def:"talks about something happening now",
    examples:["walks","eats","sees","runs"],
    pa:"ਵਰਤਮਾਨ ਕਾਲ" },
  { term:"future tense", def:"talks about something that will happen",
    examples:["will walk","will eat","will see","will run"],
    pa:"ਭਵਿੱਖ ਕਾਲ" },
  { term:"singular", def:"one of something",
    examples:["a cat","one book","the boy","a star"],
    pa:"ਇੱਕਵਚਨ" },
  { term:"plural", def:"more than one of something",
    examples:["cats","books","boys","stars"],
    pa:"ਬਹੁਵਚਨ" },
  { term:"common noun", def:"a regular noun for any person, place, or thing",
    examples:["city","dog","river","teacher"],
    pa:"ਆਮ ਨਾਂਵ" },
  { term:"proper noun", def:"the special name of one person, place, or thing — starts with a capital",
    examples:["India","Goku","Monday","Riya"],
    pa:"ਖਾਸ ਨਾਂਵ" },
  { term:"subject", def:"the noun that does the action in a sentence",
    examples:["The dog ran.","Riya sings.","Birds fly.","I read."],
    pa:"ਕਰਤਾ" },
  { term:"object", def:"the noun that gets the action in a sentence",
    examples:["I eat an apple.","She read the book.","He kicks a ball."],
    pa:"ਕਰਮ" },
  { term:"article", def:"a small word that goes before a noun: a, an, the",
    examples:["a dog","an apple","the sun"],
    pa:"ਆਰਟੀਕਲ" },
  { term:"conjunction", def:"a word that joins parts of a sentence",
    examples:["and","but","or","because"],
    pa:"ਯੋਜਕ" },
  { term:"interjection", def:"a short word that shows feeling",
    examples:["Wow!","Oh!","Yay!","Oops!"],
    pa:"ਵਿਸਮਿਕ" },
  { term:"question", def:"a sentence that asks something — ends with ?",
    examples:["What is your name?","Where is mom?","Why is it cold?"],
    pa:"ਪ੍ਰਸ਼ਨ" },
  { term:"statement", def:"a sentence that tells something — ends with .",
    examples:["I am happy.","The sun is bright.","Dogs bark."],
    pa:"ਕਥਨ" },
  { term:"exclamation", def:"a sentence that shows strong feeling — ends with !",
    examples:["What a day!","How fun!","Wow, amazing!"],
    pa:"ਵਿਸਮਾਦ" },
  { term:"command", def:"a sentence that tells someone to do something",
    examples:["Sit down.","Please listen.","Open the door."],
    pa:"ਆਦੇਸ਼" },
  { term:"capital letter", def:"a big letter — used to start sentences and names",
    examples:["A","B","India","Monday"],
    pa:"ਵੱਡਾ ਅੱਖਰ" },
  { term:"period", def:"the dot at the end of a statement",
    examples:["It is sunny.","I run.","Mom is here."],
    pa:"ਪੂਰਨ ਵਿਰਾਮ" },
  { term:"question mark", def:"the punctuation at the end of a question",
    examples:["How are you?","What is it?","Why?"],
    pa:"ਪ੍ਰਸ਼ਨ ਚਿੰਨ੍ਹ" },
  { term:"comma", def:"a small mark used for short pauses or lists",
    examples:["red, blue, and green","Yes, please.","After lunch, we played."],
    pa:"ਕਾਮਾ" },
  { term:"vowel", def:"the letters a, e, i, o, u",
    examples:["a","e","i","o","u"],
    pa:"ਸਵਰ" },
  { term:"consonant", def:"any letter that is not a vowel",
    examples:["b","c","d","f","g"],
    pa:"ਵਿਅੰਜਨ" },
  { term:"syllable", def:"a chunk of sound in a word",
    examples:["cat (1)","happy (2)","banana (3)"],
    pa:"ਅੱਖਰ-ਖੰਡ" },
  { term:"rhyme", def:"words that end with the same sound",
    examples:["cat & hat","sun & fun","tree & bee"],
    pa:"ਤੁਕਾਂਤ" },
  { term:"opposite", def:"a word that means the other way",
    examples:["hot/cold","big/small","day/night"],
    pa:"ਉਲਟ" },
  { term:"synonym", def:"a word that means about the same thing",
    examples:["big/large","happy/glad","small/tiny"],
    pa:"ਪ੍ਰਯਾਏ" },
  { term:"antonym", def:"a word that means the opposite",
    examples:["up/down","old/new","fast/slow"],
    pa:"ਵਿਪਰੀਤਾਰਥਕ" },
  { term:"contraction", def:"two words joined together with an apostrophe",
    examples:["don't (do not)","I'm (I am)","it's (it is)"],
    pa:"ਸੰਖੇਪ ਰੂਪ" },
  { term:"plural -s", def:"add s to most words to mean more than one",
    examples:["cat → cats","book → books","dog → dogs"],
    pa:"ਬਹੁਵਚਨ -s" }
];

// ---- Tagged sentences for "find the verb / noun" battle questions ----
// Each: text, plus indexes (in the words array) of the noun and the verb.
const SENTENCES = [
  { text:"The dog runs fast.",         nounIdx:1, verbIdx:2 },
  { text:"My sister sings songs.",     nounIdx:1, verbIdx:2 },
  { text:"A bird flew away.",          nounIdx:1, verbIdx:2 },
  { text:"The boy reads a book.",      nounIdx:1, verbIdx:2 },
  { text:"Children play games.",        nounIdx:0, verbIdx:1 },
  { text:"The teacher helps students.", nounIdx:1, verbIdx:2 },
  { text:"My mother cooks dinner.",     nounIdx:1, verbIdx:2 },
  { text:"The cat sleeps quietly.",     nounIdx:1, verbIdx:2 },
  { text:"Goku trains every day.",      nounIdx:0, verbIdx:1 },
  { text:"The sun shines brightly.",    nounIdx:1, verbIdx:2 },
  { text:"Rain falls softly.",          nounIdx:0, verbIdx:1 },
  { text:"The dragon flies high.",      nounIdx:1, verbIdx:2 },
  { text:"My friend laughs loudly.",    nounIdx:1, verbIdx:2 },
  { text:"The car stops suddenly.",     nounIdx:1, verbIdx:2 },
  { text:"Birds build nests.",          nounIdx:0, verbIdx:1 },
  { text:"The baby cries softly.",      nounIdx:1, verbIdx:2 },
  { text:"My father drives a truck.",   nounIdx:1, verbIdx:2 },
  { text:"The river flows fast.",       nounIdx:1, verbIdx:2 },
  { text:"Students study hard.",         nounIdx:0, verbIdx:1 },
  { text:"The horse jumps high.",       nounIdx:1, verbIdx:2 },
  { text:"The wind blows softly.",      nounIdx:1, verbIdx:2 },
  { text:"My brother climbs trees.",    nounIdx:1, verbIdx:2 },
  { text:"The fish swims slowly.",      nounIdx:1, verbIdx:2 },
  { text:"Snow melts in spring.",       nounIdx:0, verbIdx:1 },
  { text:"The bell rings loudly.",      nounIdx:1, verbIdx:2 },
  // ---- More tagged sentences ----
  { text:"The teacher writes on the board.", nounIdx:1, verbIdx:2 },
  { text:"My grandma bakes cookies.",        nounIdx:1, verbIdx:2 },
  { text:"The farmer plants seeds.",         nounIdx:1, verbIdx:2 },
  { text:"The wolf howls at night.",         nounIdx:1, verbIdx:2 },
  { text:"Stars shine brightly.",            nounIdx:0, verbIdx:1 },
  { text:"The clock ticks slowly.",          nounIdx:1, verbIdx:2 },
  { text:"My uncle paints pictures.",        nounIdx:1, verbIdx:2 },
  { text:"The frog jumps high.",             nounIdx:1, verbIdx:2 },
  { text:"My cousin plays guitar.",          nounIdx:1, verbIdx:2 },
  { text:"The leaves fall in autumn.",       nounIdx:1, verbIdx:2 },
  { text:"The chef cooks pasta.",            nounIdx:1, verbIdx:2 },
  { text:"The doctor helps patients.",       nounIdx:1, verbIdx:2 },
  { text:"My team won the match.",           nounIdx:1, verbIdx:2 },
  { text:"The artist drew a portrait.",      nounIdx:1, verbIdx:2 },
  { text:"The rocket flew to space.",        nounIdx:1, verbIdx:2 },
  { text:"Fish swim in rivers.",             nounIdx:0, verbIdx:1 },
  { text:"The puppy chases butterflies.",    nounIdx:1, verbIdx:2 }
];

// ---- Vocabulary: simple words with kid-friendly definitions ----
// Used for "Which word means…?" battle questions and as Train cards.
const VOCAB = [
  // Adjectives
  { word:"happy",    def:"feeling good and cheerful",            pa:"ਖੁਸ਼",       emoji:"😀", type:"adjective" },
  { word:"sad",      def:"feeling unhappy or low",               pa:"ਉਦਾਸ",       emoji:"😢", type:"adjective" },
  { word:"angry",    def:"feeling very upset",                   pa:"ਗੁੱਸੇ",      emoji:"😠", type:"adjective" },
  { word:"tired",    def:"feeling like you need rest",           pa:"ਥੱਕੇ",       emoji:"😪", type:"adjective" },
  { word:"hungry",   def:"feeling like you want food",           pa:"ਭੁੱਖੇ",       emoji:"🍽️", type:"adjective" },
  { word:"thirsty",  def:"feeling like you want a drink",        pa:"ਪਿਆਸੇ",      emoji:"🥤", type:"adjective" },
  { word:"big",      def:"large in size",                        pa:"ਵੱਡਾ",       emoji:"🐘", type:"adjective" },
  { word:"small",    def:"little in size",                       pa:"ਛੋਟਾ",       emoji:"🐜", type:"adjective" },
  { word:"tall",     def:"high from top to bottom",              pa:"ਉੱਚਾ",       emoji:"🦒", type:"adjective" },
  { word:"short",    def:"not tall or not long",                 pa:"ਛੋਟਾ",       emoji:"📏", type:"adjective" },
  { word:"fast",     def:"moving quickly",                       pa:"ਤੇਜ਼",       emoji:"💨", type:"adjective" },
  { word:"slow",     def:"not moving quickly",                   pa:"ਹੌਲੀ",       emoji:"🐌", type:"adjective" },
  { word:"hot",      def:"having a high temperature",            pa:"ਗਰਮ",        emoji:"🔥", type:"adjective" },
  { word:"cold",     def:"having a low temperature",             pa:"ਠੰਡਾ",       emoji:"❄️", type:"adjective" },
  { word:"old",      def:"having lived for many years",          pa:"ਪੁਰਾਣਾ",     emoji:"👴", type:"adjective" },
  { word:"young",    def:"not old; new in life",                 pa:"ਜਵਾਨ",       emoji:"👶", type:"adjective" },
  { word:"new",      def:"just made or just begun",              pa:"ਨਵਾਂ",       emoji:"🆕", type:"adjective" },
  { word:"loud",     def:"making a big sound",                   pa:"ਉੱਚੀ ਆਵਾਜ਼", emoji:"📢", type:"adjective" },
  { word:"quiet",    def:"making little or no sound",            pa:"ਚੁੱਪ",       emoji:"🤫", type:"adjective" },
  { word:"brave",    def:"not afraid when things are hard",      pa:"ਬਹਾਦਰ",      emoji:"🦁", type:"adjective" },
  { word:"kind",     def:"nice and caring to others",            pa:"ਦਿਆਲੂ",     emoji:"💗", type:"adjective" },
  { word:"smart",    def:"good at thinking and learning",        pa:"ਚਤੁਰ",       emoji:"🧠", type:"adjective" },
  { word:"funny",    def:"making people laugh",                  pa:"ਮਜ਼ਾਕੀਆ",   emoji:"🤣", type:"adjective" },
  { word:"safe",     def:"out of danger",                        pa:"ਸੁਰੱਖਿਅਤ",  emoji:"🛡️", type:"adjective" },
  { word:"strong",   def:"able to lift or do hard things",       pa:"ਤਾਕਤਵਰ",    emoji:"💪", type:"adjective" },
  { word:"weak",     def:"not strong",                           pa:"ਕਮਜ਼ੋਰ",     emoji:"🪶", type:"adjective" },
  { word:"clean",    def:"free of dirt",                         pa:"ਸਾਫ਼",        emoji:"🧼", type:"adjective" },
  { word:"dirty",    def:"covered in dirt",                      pa:"ਮੈਲਾ",       emoji:"💩", type:"adjective" },
  { word:"empty",    def:"having nothing inside",                pa:"ਖਾਲੀ",       emoji:"🪣", type:"adjective" },
  { word:"full",     def:"having no more space inside",          pa:"ਭਰਿਆ",       emoji:"📦", type:"adjective" },
  // Common everyday words
  { word:"today",    def:"this day right now",                   pa:"ਅੱਜ",        emoji:"📅", type:"word" },
  { word:"tomorrow", def:"the day after today",                  pa:"ਕੱਲ੍ਹ",      emoji:"📆", type:"word" },
  { word:"yesterday",def:"the day before today",                 pa:"ਬੀਤੇ ਕੱਲ੍ਹ", emoji:"⏳", type:"word" },
  { word:"morning",  def:"the early part of the day",            pa:"ਸਵੇਰ",       emoji:"🌅", type:"word" },
  { word:"night",    def:"the dark part of a day",               pa:"ਰਾਤ",        emoji:"🌙", type:"word" },
  { word:"week",     def:"seven days in a row",                  pa:"ਹਫ਼ਤਾ",      emoji:"📅", type:"word" },
  { word:"year",     def:"twelve months long",                   pa:"ਸਾਲ",        emoji:"🗓️", type:"word" },
  { word:"hour",     def:"sixty minutes long",                   pa:"ਘੰਟਾ",       emoji:"⏰", type:"word" },
  { word:"minute",   def:"sixty seconds long",                   pa:"ਮਿੰਟ",       emoji:"⏱️", type:"word" },
  { word:"left",     def:"the side opposite of right",           pa:"ਖੱਬੇ",       emoji:"⬅️", type:"word" },
  { word:"right",    def:"the side opposite of left",            pa:"ਸੱਜੇ",       emoji:"➡️", type:"word" },
  { word:"up",       def:"toward the sky",                       pa:"ਉੱਪਰ",       emoji:"⬆️", type:"word" },
  { word:"down",     def:"toward the ground",                    pa:"ਹੇਠਾਂ",       emoji:"⬇️", type:"word" },
  { word:"under",    def:"below something",                      pa:"ਹੇਠਾਂ",      emoji:"⬇️", type:"word" },
  { word:"above",    def:"higher than something",                pa:"ਉੱਪਰ",       emoji:"⬆️", type:"word" },
  { word:"between",  def:"in the middle of two things",          pa:"ਵਿਚਕਾਰ",    emoji:"↔️", type:"word" },
  // ---- Colors ----
  { word:"red",      def:"the color of a strawberry",            pa:"ਲਾਲ",        emoji:"🟥", type:"color" },
  { word:"blue",     def:"the color of the sky on a clear day",   pa:"ਨੀਲਾ",       emoji:"🟦", type:"color" },
  { word:"green",    def:"the color of grass and leaves",         pa:"ਹਰਾ",        emoji:"🟩", type:"color" },
  { word:"yellow",   def:"the color of the sun and bananas",      pa:"ਪੀਲਾ",       emoji:"🟨", type:"color" },
  { word:"orange",   def:"the color between red and yellow",      pa:"ਸੰਤਰੀ",      emoji:"🟧", type:"color" },
  { word:"purple",   def:"the color of grapes and plums",         pa:"ਜਾਮਣੀ",      emoji:"🟪", type:"color" },
  { word:"pink",     def:"a soft light red color",                pa:"ਗੁਲਾਬੀ",     emoji:"🌸", type:"color" },
  { word:"brown",    def:"the color of dirt or chocolate",         pa:"ਭੂਰਾ",       emoji:"🟫", type:"color" },
  { word:"black",    def:"the darkest color",                     pa:"ਕਾਲਾ",       emoji:"⬛", type:"color" },
  { word:"white",    def:"the lightest color, like snow",          pa:"ਚਿੱਟਾ",      emoji:"⬜", type:"color" },
  { word:"gray",     def:"a color between black and white",        pa:"ਸਲੇਟੀ",      emoji:"🌫️", type:"color" },
  { word:"gold",     def:"a shiny yellow color",                  pa:"ਸੁਨਹਿਰੀ",   emoji:"🟡", type:"color" },
  { word:"silver",   def:"a shiny gray color",                    pa:"ਚਾਂਦੀ",      emoji:"⚪", type:"color" },
  // ---- Shapes ----
  { word:"circle",   def:"a round shape with no corners",         pa:"ਚੱਕਰ",       emoji:"⭕", type:"shape" },
  { word:"square",   def:"a shape with four equal sides",          pa:"ਚੌਰਸ",       emoji:"🟦", type:"shape" },
  { word:"triangle", def:"a shape with three sides",               pa:"ਤਿਕੋਣ",      emoji:"🔺", type:"shape" },
  { word:"rectangle",def:"a shape with four sides, two long & two short", pa:"ਆਇਤਕਾਰ", emoji:"▭", type:"shape" },
  { word:"oval",     def:"a stretched circle, like an egg",         pa:"ਅੰਡਾਕਾਰ",   emoji:"⬭", type:"shape" },
  { word:"star",     def:"a shape with five or more points",        pa:"ਤਾਰਾ",       emoji:"⭐", type:"shape" },
  { word:"heart",    def:"a love-shaped figure",                   pa:"ਦਿਲ",        emoji:"💗", type:"shape" },
  { word:"diamond",  def:"a square turned on its corner",          pa:"ਹੀਰਾ",       emoji:"🔷", type:"shape" },
  // ---- Numbers ----
  { word:"one",      def:"the number 1",                          pa:"ਇੱਕ",        emoji:"1️⃣", type:"number" },
  { word:"two",      def:"the number 2",                          pa:"ਦੋ",         emoji:"2️⃣", type:"number" },
  { word:"three",    def:"the number 3",                          pa:"ਤਿੰਨ",       emoji:"3️⃣", type:"number" },
  { word:"four",     def:"the number 4",                          pa:"ਚਾਰ",        emoji:"4️⃣", type:"number" },
  { word:"five",     def:"the number 5",                          pa:"ਪੰਜ",        emoji:"5️⃣", type:"number" },
  { word:"six",      def:"the number 6",                          pa:"ਛੇ",         emoji:"6️⃣", type:"number" },
  { word:"seven",    def:"the number 7",                          pa:"ਸੱਤ",        emoji:"7️⃣", type:"number" },
  { word:"eight",    def:"the number 8",                          pa:"ਅੱਠ",        emoji:"8️⃣", type:"number" },
  { word:"nine",     def:"the number 9",                          pa:"ਨੌਂ",        emoji:"9️⃣", type:"number" },
  { word:"ten",      def:"the number 10",                         pa:"ਦਸ",         emoji:"🔟", type:"number" },
  { word:"hundred",  def:"the number 100",                         pa:"ਸੌ",         emoji:"💯", type:"number" },
  { word:"thousand", def:"the number 1,000",                       pa:"ਹਜ਼ਾਰ",      emoji:"🔢", type:"number" },
  { word:"first",    def:"the one before all others",              pa:"ਪਹਿਲਾ",     emoji:"🥇", type:"number" },
  { word:"second",   def:"the one right after first",              pa:"ਦੂਜਾ",       emoji:"🥈", type:"number" },
  { word:"third",    def:"the one right after second",             pa:"ਤੀਜਾ",       emoji:"🥉", type:"number" },
  { word:"last",     def:"the one at the end",                     pa:"ਆਖਰੀ",       emoji:"🏁", type:"number" },
  // ---- Days of the week ----
  { word:"Monday",    def:"the first weekday",                    pa:"ਸੋਮਵਾਰ",     emoji:"📅", type:"day" },
  { word:"Tuesday",   def:"the day after Monday",                  pa:"ਮੰਗਲਵਾਰ",    emoji:"📅", type:"day" },
  { word:"Wednesday", def:"the middle of the work week",           pa:"ਬੁੱਧਵਾਰ",    emoji:"📅", type:"day" },
  { word:"Thursday",  def:"the day after Wednesday",                pa:"ਵੀਰਵਾਰ",     emoji:"📅", type:"day" },
  { word:"Friday",    def:"the last weekday before the weekend",    pa:"ਸ਼ੁੱਕਰਵਾਰ", emoji:"📅", type:"day" },
  { word:"Saturday",  def:"a weekend day",                         pa:"ਸ਼ਨੀਵਾਰ",   emoji:"🎉", type:"day" },
  { word:"Sunday",    def:"a weekend day, often for rest",          pa:"ਐਤਵਾਰ",       emoji:"🎉", type:"day" },
  // ---- Months ----
  { word:"January",   def:"the first month of the year",            pa:"ਜਨਵਰੀ",     emoji:"🗓️", type:"month" },
  { word:"February",  def:"the second month — the shortest",         pa:"ਫਰਵਰੀ",      emoji:"🗓️", type:"month" },
  { word:"March",     def:"the third month — spring begins",         pa:"ਮਾਰਚ",       emoji:"🗓️", type:"month" },
  { word:"April",     def:"the fourth month",                       pa:"ਅਪ੍ਰੈਲ",     emoji:"🗓️", type:"month" },
  { word:"May",       def:"the fifth month",                        pa:"ਮਈ",         emoji:"🗓️", type:"month" },
  { word:"June",      def:"the sixth month — summer begins",         pa:"ਜੂਨ",        emoji:"🗓️", type:"month" },
  { word:"July",      def:"the seventh month",                      pa:"ਜੁਲਾਈ",      emoji:"🗓️", type:"month" },
  { word:"August",    def:"the eighth month",                       pa:"ਅਗਸਤ",       emoji:"🗓️", type:"month" },
  { word:"September", def:"the ninth month — autumn begins",         pa:"ਸਤੰਬਰ",      emoji:"🗓️", type:"month" },
  { word:"October",   def:"the tenth month",                        pa:"ਅਕਤੂਬਰ",     emoji:"🗓️", type:"month" },
  { word:"November",  def:"the eleventh month",                     pa:"ਨਵੰਬਰ",      emoji:"🗓️", type:"month" },
  { word:"December",  def:"the last month — winter",                 pa:"ਦਸੰਬਰ",      emoji:"🗓️", type:"month" },
  // ---- Weather ----
  { word:"rain",     def:"water that falls from clouds",           pa:"ਮੀਂਹ",       emoji:"🌧️", type:"weather" },
  { word:"snow",     def:"soft white flakes that fall when it's cold", pa:"ਬਰਫ਼", emoji:"❄️", type:"weather" },
  { word:"wind",     def:"air that moves",                         pa:"ਹਵਾ",        emoji:"💨", type:"weather" },
  { word:"storm",    def:"strong wind and rain together",          pa:"ਤੂਫ਼ਾਨ",     emoji:"⛈️", type:"weather" },
  { word:"sunny",    def:"when the sun shines bright",             pa:"ਧੁੱਪਦਾਰ",   emoji:"🌞", type:"weather" },
  { word:"cloudy",   def:"when the sky has lots of clouds",         pa:"ਬੱਦਲਵਾਈ",   emoji:"☁️", type:"weather" },
  { word:"rainbow",  def:"a colorful arc in the sky after rain",    pa:"ਸਤਰੰਗੀ",     emoji:"🌈", type:"weather" },
  { word:"thunder",  def:"the loud sound during a storm",           pa:"ਗਰਜ",        emoji:"⚡", type:"weather" },
  { word:"lightning",def:"a flash of light during a storm",          pa:"ਬਿਜਲੀ",      emoji:"⚡", type:"weather" },
  { word:"fog",      def:"a thick cloud near the ground",           pa:"ਧੁੰਦ",       emoji:"🌫️", type:"weather" },
  // ---- More feelings ----
  { word:"excited",  def:"feeling very happy about something",      pa:"ਉਤਸੁਕ",      emoji:"🤩", type:"adjective" },
  { word:"scared",   def:"feeling afraid",                         pa:"ਡਰਿਆ",       emoji:"😨", type:"adjective" },
  { word:"shy",      def:"feeling quiet around new people",         pa:"ਸ਼ਰਮੀਲਾ",   emoji:"😳", type:"adjective" },
  { word:"proud",    def:"feeling good about what you did",          pa:"ਮਾਣਮੱਤਾ",   emoji:"🦚", type:"adjective" },
  { word:"calm",     def:"feeling quiet and peaceful inside",        pa:"ਸ਼ਾਂਤ",      emoji:"🧘", type:"adjective" },
  { word:"silly",    def:"acting playful and a bit funny",           pa:"ਮਜ਼ਾਕੀਆ",   emoji:"🤪", type:"adjective" },
  { word:"bored",    def:"feeling like there's nothing fun to do",   pa:"ਬੇਚੈਨ",      emoji:"😑", type:"adjective" },
  { word:"surprised",def:"feeling shocked by something new",         pa:"ਹੈਰਾਨ",      emoji:"😲", type:"adjective" },
  // ---- More common words ----
  { word:"always",   def:"every time, all the time",                pa:"ਹਮੇਸ਼ਾ",     emoji:"♾️", type:"adverb" },
  { word:"never",    def:"not at any time",                          pa:"ਕਦੇ ਨਹੀਂ",   emoji:"🚫", type:"adverb" },
  { word:"often",    def:"many times",                              pa:"ਅਕਸਰ",       emoji:"🔁", type:"adverb" },
  { word:"sometimes",def:"once in a while",                          pa:"ਕਦੇ ਕਦੇ",    emoji:"⏳", type:"adverb" },
  { word:"early",    def:"before the usual time",                    pa:"ਜਲਦੀ",       emoji:"🌅", type:"adverb" },
  { word:"late",     def:"after the usual time",                     pa:"ਦੇਰ",        emoji:"⌛", type:"adverb" },
  { word:"slowly",   def:"in a slow way",                            pa:"ਹੌਲੀ",       emoji:"🐢", type:"adverb" },
  { word:"quickly",  def:"in a fast way",                            pa:"ਜਲਦੀ",       emoji:"⚡", type:"adverb" },
  { word:"loudly",   def:"in a loud way",                            pa:"ਉੱਚੀ",       emoji:"📢", type:"adverb" },
  { word:"softly",   def:"in a quiet, gentle way",                   pa:"ਹੌਲੀ",       emoji:"🤫", type:"adverb" },
  { word:"hello",    def:"a friendly greeting",                      pa:"ਸਤ ਸ੍ਰੀ ਅਕਾਲ", emoji:"👋", type:"word" },
  { word:"goodbye",  def:"what you say when leaving",                pa:"ਅਲਵਿਦਾ",     emoji:"👋", type:"word" },
  { word:"please",   def:"a polite word when asking for something",   pa:"ਕਿਰਪਾ ਕਰਕੇ", emoji:"🙏", type:"word" },
  { word:"thanks",   def:"a word to show you are grateful",           pa:"ਧੰਨਵਾਦ",     emoji:"🙏", type:"word" },
  { word:"sorry",    def:"a word to say when you make a mistake",     pa:"ਮਾਫ਼ੀ",      emoji:"😔", type:"word" },
  { word:"yes",      def:"a word that means agree",                  pa:"ਹਾਂ",        emoji:"✅", type:"word" },
  { word:"no",       def:"a word that means disagree",               pa:"ਨਹੀਂ",       emoji:"❌", type:"word" },
  { word:"maybe",    def:"could be yes or no — not sure",            pa:"ਸ਼ਾਇਦ",      emoji:"🤔", type:"word" },
  { word:"more",     def:"a bigger amount",                         pa:"ਵੱਧ",        emoji:"➕", type:"word" },
  { word:"less",     def:"a smaller amount",                        pa:"ਘੱਟ",        emoji:"➖", type:"word" },
  { word:"every",    def:"each one of them",                        pa:"ਹਰ",         emoji:"🌐", type:"word" },
  { word:"some",     def:"a few but not all",                       pa:"ਕੁਝ",        emoji:"🍽️", type:"word" },
  { word:"many",     def:"a large number",                          pa:"ਬਹੁਤ",       emoji:"🔢", type:"word" },
  { word:"few",      def:"a small number",                          pa:"ਥੋੜ੍ਹੇ",     emoji:"🤏", type:"word" },
  { word:"because",  def:"a word that gives a reason",               pa:"ਕਿਉਂਕਿ",     emoji:"💡", type:"word" },
  { word:"if",       def:"a word that shows a possibility",          pa:"ਜੇ",         emoji:"❓", type:"word" },
  { word:"and",      def:"a word that joins two things",             pa:"ਅਤੇ",        emoji:"➕", type:"word" },
  { word:"but",      def:"a word that shows a difference",           pa:"ਪਰ",         emoji:"↔️", type:"word" }
];
